CALL C:\Users\JMCNEILAN\Documents\Projects\Python\DFH_Integra\UI\interfaces\pyuic5.bat -x Dialog_NewItem.ui -o Dialog_NewItem.py
CALL C:\Users\JMCNEILAN\Documents\Projects\Python\DFH_Integra\UI\interfaces\pyuic5.bat -x Dialog_NewLot.ui -o Dialog_NewLot.py
CALL C:\Users\JMCNEILAN\Documents\Projects\Python\DFH_Integra\UI\interfaces\pyuic5.bat -x Dialog_AssaySpec.ui -o Dialog_AssaySpec.py
CALL C:\Users\JMCNEILAN\Documents\Projects\Python\DFH_Integra\UI\interfaces\pyuic5.bat -x Dialog_BasicSpec.ui -o Dialog_BasicSpec.py
CALL C:\Users\JMCNEILAN\Documents\Projects\Python\DFH_Integra\UI\interfaces\pyuic5.bat -x Dialog_ChemSpec.ui -o Dialog_ChemSpec.py
CALL C:\Users\JMCNEILAN\Documents\Projects\Python\DFH_Integra\UI\interfaces\pyuic5.bat -x Dialog_HMSpec.ui -o Dialog_HMSpec.py
CALL C:\Users\JMCNEILAN\Documents\Projects\Python\DFH_Integra\UI\interfaces\pyuic5.bat -x Dialog_MicroSpec.ui -o Dialog_MicroSpec.py
CALL C:\Users\JMCNEILAN\Documents\Projects\Python\DFH_Integra\UI\interfaces\pyuic5.bat -x Dialog_OrganolepticSpec.ui -o Dialog_OrganolepticSpec.py
CALL C:\Users\JMCNEILAN\Documents\Projects\Python\DFH_Integra\UI\interfaces\pyuic5.bat -x Dialog_PesticideSpec.ui -o Dialog_PesticideSpec.py
CALL C:\Users\JMCNEILAN\Documents\Projects\Python\DFH_Integra\UI\interfaces\pyuic5.bat -x Dialog_PhysicalSpec.ui -o Dialog_PhysicalSpec.py
CALL C:\Users\JMCNEILAN\Documents\Projects\Python\DFH_Integra\UI\interfaces\pyuic5.bat -x Dialog_PlantSpec.ui -o Dialog_PlantSpec.py
CALL C:\Users\JMCNEILAN\Documents\Projects\Python\DFH_Integra\UI\interfaces\pyuic5.bat -x Dialog_TextOnly.ui -o Dialog_TextOnly.py
