# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dialog_BasicSpec.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(271, 347)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_6 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_6.setObjectName("groupBox_6")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_6)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox_6)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.is_item_numberLE = QtWidgets.QLineEdit(self.groupBox_6)
        self.is_item_numberLE.setEnabled(False)
        self.is_item_numberLE.setInputMethodHints(QtCore.Qt.ImhNone)
        self.is_item_numberLE.setObjectName("is_item_numberLE")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.is_item_numberLE)
        self.label_2 = QtWidgets.QLabel(self.groupBox_6)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.is_item_nameLE = QtWidgets.QLineEdit(self.groupBox_6)
        self.is_item_nameLE.setObjectName("is_item_nameLE")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.is_item_nameLE)
        self.label_4 = QtWidgets.QLabel(self.groupBox_6)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.label_4)
        self.is_item_notePT = QtWidgets.QPlainTextEdit(self.groupBox_6)
        self.is_item_notePT.setObjectName("is_item_notePT")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.is_item_notePT)
        self.gridLayout.addWidget(self.groupBox_6, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout_2.setObjectName("formLayout_2")
        self.is_fridgeCB = QtWidgets.QCheckBox(self.groupBox)
        self.is_fridgeCB.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.is_fridgeCB.setObjectName("is_fridgeCB")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.is_fridgeCB)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_7.addWidget(self.label_3)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.is_eggCB = QtWidgets.QCheckBox(self.groupBox)
        self.is_eggCB.setObjectName("is_eggCB")
        self.gridLayout_3.addWidget(self.is_eggCB, 0, 0, 1, 1)
        self.is_peanutCB = QtWidgets.QCheckBox(self.groupBox)
        self.is_peanutCB.setObjectName("is_peanutCB")
        self.gridLayout_3.addWidget(self.is_peanutCB, 0, 1, 1, 1)
        self.is_soyCB = QtWidgets.QCheckBox(self.groupBox)
        self.is_soyCB.setObjectName("is_soyCB")
        self.gridLayout_3.addWidget(self.is_soyCB, 0, 2, 1, 1)
        self.is_shellfishCB = QtWidgets.QCheckBox(self.groupBox)
        self.is_shellfishCB.setObjectName("is_shellfishCB")
        self.gridLayout_3.addWidget(self.is_shellfishCB, 0, 3, 1, 1)
        self.is_fishCB = QtWidgets.QCheckBox(self.groupBox)
        self.is_fishCB.setObjectName("is_fishCB")
        self.gridLayout_3.addWidget(self.is_fishCB, 1, 0, 1, 1)
        self.is_wheatCB = QtWidgets.QCheckBox(self.groupBox)
        self.is_wheatCB.setObjectName("is_wheatCB")
        self.gridLayout_3.addWidget(self.is_wheatCB, 1, 1, 1, 1)
        self.is_milkCB = QtWidgets.QCheckBox(self.groupBox)
        self.is_milkCB.setObjectName("is_milkCB")
        self.gridLayout_3.addWidget(self.is_milkCB, 1, 2, 1, 1)
        self.is_treenutCB = QtWidgets.QCheckBox(self.groupBox)
        self.is_treenutCB.setObjectName("is_treenutCB")
        self.gridLayout_3.addWidget(self.is_treenutCB, 1, 3, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_3)
        self.formLayout_2.setLayout(1, QtWidgets.QFormLayout.LabelRole, self.verticalLayout_7)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 1)
        self.acceptB = QtWidgets.QDialogButtonBox(Dialog)
        self.acceptB.setOrientation(QtCore.Qt.Horizontal)
        self.acceptB.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.acceptB.setObjectName("acceptB")
        self.gridLayout.addWidget(self.acceptB, 2, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.acceptB.accepted.connect(Dialog.accept)
        self.acceptB.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.is_item_numberLE, self.is_item_nameLE)
        Dialog.setTabOrder(self.is_item_nameLE, self.is_item_notePT)
        Dialog.setTabOrder(self.is_item_notePT, self.is_fridgeCB)
        Dialog.setTabOrder(self.is_fridgeCB, self.is_eggCB)
        Dialog.setTabOrder(self.is_eggCB, self.is_peanutCB)
        Dialog.setTabOrder(self.is_peanutCB, self.is_soyCB)
        Dialog.setTabOrder(self.is_soyCB, self.is_shellfishCB)
        Dialog.setTabOrder(self.is_shellfishCB, self.is_fishCB)
        Dialog.setTabOrder(self.is_fishCB, self.is_wheatCB)
        Dialog.setTabOrder(self.is_wheatCB, self.is_milkCB)
        Dialog.setTabOrder(self.is_milkCB, self.is_treenutCB)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox_6.setTitle(_translate("Dialog", "Basic Info:"))
        self.label.setText(_translate("Dialog", "Item #:"))
        self.label_2.setText(_translate("Dialog", "Name:"))
        self.label_4.setText(_translate("Dialog", "Item notes:"))
        self.groupBox.setTitle(_translate("Dialog", "Storage"))
        self.is_fridgeCB.setText(_translate("Dialog", "Requires refridgeration?"))
        self.label_3.setText(_translate("Dialog", "FDA-8 Allergens:"))
        self.is_eggCB.setText(_translate("Dialog", "Egg"))
        self.is_peanutCB.setText(_translate("Dialog", "Peanut"))
        self.is_soyCB.setText(_translate("Dialog", "Soy"))
        self.is_shellfishCB.setText(_translate("Dialog", "Shellfish"))
        self.is_fishCB.setText(_translate("Dialog", "Fish"))
        self.is_wheatCB.setText(_translate("Dialog", "Wheat"))
        self.is_milkCB.setText(_translate("Dialog", "Milk"))
        self.is_treenutCB.setText(_translate("Dialog", "Tree Nut"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

