# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dialog_NewItem.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(507, 453)
        self.gridLayout_4 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem, 4, 1, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_6.setObjectName("groupBox_6")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_6)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox_6)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.is_item_numberLE = QtWidgets.QLineEdit(self.groupBox_6)
        self.is_item_numberLE.setEnabled(True)
        self.is_item_numberLE.setInputMethodHints(QtCore.Qt.ImhNone)
        self.is_item_numberLE.setObjectName("is_item_numberLE")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.is_item_numberLE)
        self.label_2 = QtWidgets.QLabel(self.groupBox_6)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.is_item_nameLE = QtWidgets.QLineEdit(self.groupBox_6)
        self.is_item_nameLE.setObjectName("is_item_nameLE")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.is_item_nameLE)
        self.label_4 = QtWidgets.QLabel(self.groupBox_6)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.label_4)
        self.is_item_notePT = QtWidgets.QPlainTextEdit(self.groupBox_6)
        self.is_item_notePT.setObjectName("is_item_notePT")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.is_item_notePT)
        self.gridLayout_4.addWidget(self.groupBox_6, 0, 0, 2, 1)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout_2.setObjectName("formLayout_2")
        self.is_fridgeCB = QtWidgets.QCheckBox(self.groupBox)
        self.is_fridgeCB.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.is_fridgeCB.setObjectName("is_fridgeCB")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.is_fridgeCB)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_7.addWidget(self.label_3)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.is_eggCB = QtWidgets.QCheckBox(self.groupBox)
        self.is_eggCB.setObjectName("is_eggCB")
        self.gridLayout_3.addWidget(self.is_eggCB, 0, 0, 1, 1)
        self.is_peanutCB = QtWidgets.QCheckBox(self.groupBox)
        self.is_peanutCB.setObjectName("is_peanutCB")
        self.gridLayout_3.addWidget(self.is_peanutCB, 0, 1, 1, 1)
        self.is_soyCB = QtWidgets.QCheckBox(self.groupBox)
        self.is_soyCB.setObjectName("is_soyCB")
        self.gridLayout_3.addWidget(self.is_soyCB, 0, 2, 1, 1)
        self.is_shellfishCB = QtWidgets.QCheckBox(self.groupBox)
        self.is_shellfishCB.setObjectName("is_shellfishCB")
        self.gridLayout_3.addWidget(self.is_shellfishCB, 0, 3, 1, 1)
        self.is_fishCB = QtWidgets.QCheckBox(self.groupBox)
        self.is_fishCB.setObjectName("is_fishCB")
        self.gridLayout_3.addWidget(self.is_fishCB, 1, 0, 1, 1)
        self.is_wheatCB = QtWidgets.QCheckBox(self.groupBox)
        self.is_wheatCB.setObjectName("is_wheatCB")
        self.gridLayout_3.addWidget(self.is_wheatCB, 1, 1, 1, 1)
        self.is_milkCB = QtWidgets.QCheckBox(self.groupBox)
        self.is_milkCB.setObjectName("is_milkCB")
        self.gridLayout_3.addWidget(self.is_milkCB, 1, 2, 1, 1)
        self.is_treenutCB = QtWidgets.QCheckBox(self.groupBox)
        self.is_treenutCB.setObjectName("is_treenutCB")
        self.gridLayout_3.addWidget(self.is_treenutCB, 1, 3, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_3)
        self.formLayout_2.setLayout(1, QtWidgets.QFormLayout.LabelRole, self.verticalLayout_7)
        self.gridLayout_4.addWidget(self.groupBox, 3, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.is_unitCombo = QtWidgets.QComboBox(self.groupBox_2)
        self.is_unitCombo.setObjectName("is_unitCombo")
        self.is_unitCombo.addItem("")
        self.is_unitCombo.addItem("")
        self.is_unitCombo.addItem("")
        self.is_unitCombo.addItem("")
        self.is_unitCombo.addItem("")
        self.gridLayout.addWidget(self.is_unitCombo, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.is_asLE = QtWidgets.QLineEdit(self.groupBox_2)
        self.is_asLE.setObjectName("is_asLE")
        self.gridLayout.addWidget(self.is_asLE, 1, 1, 1, 1)
        self.is_unitL1 = QtWidgets.QLabel(self.groupBox_2)
        self.is_unitL1.setObjectName("is_unitL1")
        self.gridLayout.addWidget(self.is_unitL1, 1, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 0, 1, 1)
        self.is_cdLE = QtWidgets.QLineEdit(self.groupBox_2)
        self.is_cdLE.setObjectName("is_cdLE")
        self.gridLayout.addWidget(self.is_cdLE, 2, 1, 1, 1)
        self.is_unitL2 = QtWidgets.QLabel(self.groupBox_2)
        self.is_unitL2.setObjectName("is_unitL2")
        self.gridLayout.addWidget(self.is_unitL2, 2, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 3, 0, 1, 1)
        self.is_pbLE = QtWidgets.QLineEdit(self.groupBox_2)
        self.is_pbLE.setObjectName("is_pbLE")
        self.gridLayout.addWidget(self.is_pbLE, 3, 1, 1, 1)
        self.is_unitL3 = QtWidgets.QLabel(self.groupBox_2)
        self.is_unitL3.setObjectName("is_unitL3")
        self.gridLayout.addWidget(self.is_unitL3, 3, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 4, 0, 1, 1)
        self.is_hgLE = QtWidgets.QLineEdit(self.groupBox_2)
        self.is_hgLE.setObjectName("is_hgLE")
        self.gridLayout.addWidget(self.is_hgLE, 4, 1, 1, 1)
        self.is_unitL4 = QtWidgets.QLabel(self.groupBox_2)
        self.is_unitL4.setObjectName("is_unitL4")
        self.gridLayout.addWidget(self.is_unitL4, 4, 2, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 0, 1, 1)
        self.is_tpc_maxLE = QtWidgets.QLineEdit(self.groupBox_3)
        self.is_tpc_maxLE.setObjectName("is_tpc_maxLE")
        self.gridLayout_2.addWidget(self.is_tpc_maxLE, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 0, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 1, 0, 1, 1)
        self.is_ym_maxLE = QtWidgets.QLineEdit(self.groupBox_3)
        self.is_ym_maxLE.setObjectName("is_ym_maxLE")
        self.gridLayout_2.addWidget(self.is_ym_maxLE, 1, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 1, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 2, 0, 1, 1)
        self.is_ecoliCombo = QtWidgets.QComboBox(self.groupBox_3)
        self.is_ecoliCombo.setObjectName("is_ecoliCombo")
        self.is_ecoliCombo.addItem("")
        self.is_ecoliCombo.addItem("")
        self.is_ecoliCombo.addItem("")
        self.gridLayout_2.addWidget(self.is_ecoliCombo, 2, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_3)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 3, 0, 1, 1)
        self.is_salmonellaCombo = QtWidgets.QComboBox(self.groupBox_3)
        self.is_salmonellaCombo.setObjectName("is_salmonellaCombo")
        self.is_salmonellaCombo.addItem("")
        self.is_salmonellaCombo.addItem("")
        self.is_salmonellaCombo.addItem("")
        self.gridLayout_2.addWidget(self.is_salmonellaCombo, 3, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_3)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 4, 0, 1, 1)
        self.is_staphCombo = QtWidgets.QComboBox(self.groupBox_3)
        self.is_staphCombo.setObjectName("is_staphCombo")
        self.is_staphCombo.addItem("")
        self.is_staphCombo.addItem("")
        self.is_staphCombo.addItem("")
        self.gridLayout_2.addWidget(self.is_staphCombo, 4, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.groupBox_3)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 5, 0, 1, 3)
        self.label_17 = QtWidgets.QLabel(self.groupBox_3)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 6, 0, 1, 2)
        self.label_18 = QtWidgets.QLabel(self.groupBox_3)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 7, 0, 1, 1)
        self.is_tpc_minLE = QtWidgets.QLineEdit(self.groupBox_3)
        self.is_tpc_minLE.setObjectName("is_tpc_minLE")
        self.gridLayout_2.addWidget(self.is_tpc_minLE, 7, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox_3)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 7, 2, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox_3)
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 8, 0, 1, 1)
        self.is_ym_minLE = QtWidgets.QLineEdit(self.groupBox_3)
        self.is_ym_minLE.setObjectName("is_ym_minLE")
        self.gridLayout_2.addWidget(self.is_ym_minLE, 8, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupBox_3)
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 8, 2, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_3, 1, 1, 3, 1)
        self.acceptB = QtWidgets.QDialogButtonBox(Dialog)
        self.acceptB.setOrientation(QtCore.Qt.Horizontal)
        self.acceptB.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.acceptB.setObjectName("acceptB")
        self.gridLayout_4.addWidget(self.acceptB, 5, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem1, 2, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.acceptB.accepted.connect(Dialog.accept)
        self.acceptB.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.is_item_numberLE, self.is_item_nameLE)
        Dialog.setTabOrder(self.is_item_nameLE, self.is_unitCombo)
        Dialog.setTabOrder(self.is_unitCombo, self.is_asLE)
        Dialog.setTabOrder(self.is_asLE, self.is_cdLE)
        Dialog.setTabOrder(self.is_cdLE, self.is_pbLE)
        Dialog.setTabOrder(self.is_pbLE, self.is_hgLE)
        Dialog.setTabOrder(self.is_hgLE, self.is_tpc_maxLE)
        Dialog.setTabOrder(self.is_tpc_maxLE, self.is_ym_maxLE)
        Dialog.setTabOrder(self.is_ym_maxLE, self.is_ecoliCombo)
        Dialog.setTabOrder(self.is_ecoliCombo, self.is_salmonellaCombo)
        Dialog.setTabOrder(self.is_salmonellaCombo, self.is_staphCombo)
        Dialog.setTabOrder(self.is_staphCombo, self.is_tpc_minLE)
        Dialog.setTabOrder(self.is_tpc_minLE, self.is_ym_minLE)
        Dialog.setTabOrder(self.is_ym_minLE, self.is_fridgeCB)
        Dialog.setTabOrder(self.is_fridgeCB, self.is_eggCB)
        Dialog.setTabOrder(self.is_eggCB, self.is_peanutCB)
        Dialog.setTabOrder(self.is_peanutCB, self.is_soyCB)
        Dialog.setTabOrder(self.is_soyCB, self.is_shellfishCB)
        Dialog.setTabOrder(self.is_shellfishCB, self.is_fishCB)
        Dialog.setTabOrder(self.is_fishCB, self.is_wheatCB)
        Dialog.setTabOrder(self.is_wheatCB, self.is_milkCB)
        Dialog.setTabOrder(self.is_milkCB, self.is_treenutCB)
        Dialog.setTabOrder(self.is_treenutCB, self.is_item_notePT)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox_6.setTitle(_translate("Dialog", "Basic Info:"))
        self.label.setText(_translate("Dialog", "Item #:"))
        self.label_2.setText(_translate("Dialog", "Name:"))
        self.label_4.setText(_translate("Dialog", "Item notes:"))
        self.groupBox.setTitle(_translate("Dialog", "Storage"))
        self.is_fridgeCB.setText(_translate("Dialog", "Requires refridgeration?"))
        self.label_3.setText(_translate("Dialog", "FDA-8 Allergens:"))
        self.is_eggCB.setText(_translate("Dialog", "Egg"))
        self.is_peanutCB.setText(_translate("Dialog", "Peanut"))
        self.is_soyCB.setText(_translate("Dialog", "Soy"))
        self.is_shellfishCB.setText(_translate("Dialog", "Shellfish"))
        self.is_fishCB.setText(_translate("Dialog", "Fish"))
        self.is_wheatCB.setText(_translate("Dialog", "Wheat"))
        self.is_milkCB.setText(_translate("Dialog", "Milk"))
        self.is_treenutCB.setText(_translate("Dialog", "Tree Nut"))
        self.groupBox_2.setTitle(_translate("Dialog", "Heavy Metal Specifications"))
        self.label_5.setText(_translate("Dialog", "Units:"))
        self.is_unitCombo.setItemText(0, _translate("Dialog", "ppm"))
        self.is_unitCombo.setItemText(1, _translate("Dialog", "mcg/serving"))
        self.is_unitCombo.setItemText(2, _translate("Dialog", "mcg/sg"))
        self.is_unitCombo.setItemText(3, _translate("Dialog", "mcg/tablet"))
        self.is_unitCombo.setItemText(4, _translate("Dialog", "mcg/capsule"))
        self.label_6.setText(_translate("Dialog", "Arsenic less than:"))
        self.is_unitL1.setText(_translate("Dialog", "ppm"))
        self.label_7.setText(_translate("Dialog", "Cadmium less than:"))
        self.is_unitL2.setText(_translate("Dialog", "ppm"))
        self.label_8.setText(_translate("Dialog", "Lead less than:"))
        self.is_unitL3.setText(_translate("Dialog", "ppm"))
        self.label_9.setText(_translate("Dialog", "Mercury less than:"))
        self.is_unitL4.setText(_translate("Dialog", "ppm"))
        self.groupBox_3.setTitle(_translate("Dialog", "Microbial Specifications"))
        self.label_10.setText(_translate("Dialog", "TPC Max:"))
        self.label_11.setText(_translate("Dialog", "CFU/g"))
        self.label_12.setText(_translate("Dialog", "Y&M Max:"))
        self.label_13.setText(_translate("Dialog", "CFU/g"))
        self.label_14.setText(_translate("Dialog", "E. Coli:"))
        self.is_ecoliCombo.setItemText(0, _translate("Dialog", "Negative"))
        self.is_ecoliCombo.setItemText(1, _translate("Dialog", "Not Tested"))
        self.is_ecoliCombo.setItemText(2, _translate("Dialog", "Positive"))
        self.label_15.setText(_translate("Dialog", "Salmonella:"))
        self.is_salmonellaCombo.setItemText(0, _translate("Dialog", "Negative"))
        self.is_salmonellaCombo.setItemText(1, _translate("Dialog", "Not Tested"))
        self.is_salmonellaCombo.setItemText(2, _translate("Dialog", "Positive"))
        self.label_16.setText(_translate("Dialog", "Staph:"))
        self.is_staphCombo.setItemText(0, _translate("Dialog", "Negative"))
        self.is_staphCombo.setItemText(1, _translate("Dialog", "Not Tested"))
        self.is_staphCombo.setItemText(2, _translate("Dialog", "Positive"))
        self.label_17.setText(_translate("Dialog", "Probiotics Only:"))
        self.label_18.setText(_translate("Dialog", "TPC Min:"))
        self.label_19.setText(_translate("Dialog", "CFU/g"))
        self.label_20.setText(_translate("Dialog", "Y&M Min:"))
        self.label_21.setText(_translate("Dialog", "CFU/g"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

