# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dialog_PhysicalSpec.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(251, 348)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.is_moisture_minLE = QtWidgets.QLineEdit(self.groupBox)
        self.is_moisture_minLE.setObjectName("is_moisture_minLE")
        self.gridLayout.addWidget(self.is_moisture_minLE, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.is_moisture_maxLE = QtWidgets.QLineEdit(self.groupBox)
        self.is_moisture_maxLE.setObjectName("is_moisture_maxLE")
        self.gridLayout.addWidget(self.is_moisture_maxLE, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.is_tap_density_maxLE = QtWidgets.QLineEdit(self.groupBox_2)
        self.is_tap_density_maxLE.setObjectName("is_tap_density_maxLE")
        self.gridLayout_2.addWidget(self.is_tap_density_maxLE, 3, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 3, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 2, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 3, 2, 1, 1)
        self.is_tap_density_minLE = QtWidgets.QLineEdit(self.groupBox_2)
        self.is_tap_density_minLE.setObjectName("is_tap_density_minLE")
        self.gridLayout_2.addWidget(self.is_tap_density_minLE, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 0, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 1, 0, 1, 1)
        self.is_flow_density_minLE = QtWidgets.QLineEdit(self.groupBox_2)
        self.is_flow_density_minLE.setObjectName("is_flow_density_minLE")
        self.gridLayout_2.addWidget(self.is_flow_density_minLE, 0, 1, 1, 1)
        self.is_flow_density_maxLE = QtWidgets.QLineEdit(self.groupBox_2)
        self.is_flow_density_maxLE.setObjectName("is_flow_density_maxLE")
        self.gridLayout_2.addWidget(self.is_flow_density_maxLE, 1, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 1, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_2)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 0, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 0, 0, 1, 1)
        self.is_avgwt_minLE = QtWidgets.QLineEdit(self.groupBox_3)
        self.is_avgwt_minLE.setObjectName("is_avgwt_minLE")
        self.gridLayout_3.addWidget(self.is_avgwt_minLE, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 0, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 1, 0, 1, 1)
        self.is_avgwt_maxLE = QtWidgets.QLineEdit(self.groupBox_3)
        self.is_avgwt_maxLE.setObjectName("is_avgwt_maxLE")
        self.gridLayout_3.addWidget(self.is_avgwt_maxLE, 1, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 1, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.acceptB = QtWidgets.QDialogButtonBox(Dialog)
        self.acceptB.setOrientation(QtCore.Qt.Horizontal)
        self.acceptB.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.acceptB.setObjectName("acceptB")
        self.verticalLayout.addWidget(self.acceptB)

        self.retranslateUi(Dialog)
        self.acceptB.accepted.connect(Dialog.accept)
        self.acceptB.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.is_moisture_minLE, self.is_moisture_maxLE)
        Dialog.setTabOrder(self.is_moisture_maxLE, self.is_flow_density_minLE)
        Dialog.setTabOrder(self.is_flow_density_minLE, self.is_flow_density_maxLE)
        Dialog.setTabOrder(self.is_flow_density_maxLE, self.is_tap_density_minLE)
        Dialog.setTabOrder(self.is_tap_density_minLE, self.is_tap_density_maxLE)
        Dialog.setTabOrder(self.is_tap_density_maxLE, self.is_avgwt_minLE)
        Dialog.setTabOrder(self.is_avgwt_minLE, self.is_avgwt_maxLE)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "Moisture Specifications"))
        self.label.setText(_translate("Dialog", "Moisture Min:"))
        self.label_3.setText(_translate("Dialog", "%"))
        self.label_2.setText(_translate("Dialog", "Moisture Max:"))
        self.label_4.setText(_translate("Dialog", "%"))
        self.groupBox_2.setTitle(_translate("Dialog", "Density Specifications"))
        self.label_6.setText(_translate("Dialog", "Tap Density Max:"))
        self.label_7.setText(_translate("Dialog", "g/mL"))
        self.label_8.setText(_translate("Dialog", "g/mL"))
        self.label_5.setText(_translate("Dialog", "Tap Density Min:"))
        self.label_13.setText(_translate("Dialog", "Flow Density Min:"))
        self.label_14.setText(_translate("Dialog", "Flow Density Max:"))
        self.label_15.setText(_translate("Dialog", "g/mL"))
        self.label_16.setText(_translate("Dialog", "g/mL"))
        self.groupBox_3.setTitle(_translate("Dialog", "Average Weight Specifications"))
        self.label_9.setText(_translate("Dialog", "Avg. Wt. Min:"))
        self.label_11.setText(_translate("Dialog", "grams"))
        self.label_10.setText(_translate("Dialog", "Avg. Wt. Max:"))
        self.label_12.setText(_translate("Dialog", "grams"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

