# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dialog_AssaySpec.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(265, 259)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.is_unitCombo = QtWidgets.QComboBox(self.groupBox)
        self.is_unitCombo.setObjectName("is_unitCombo")
        self.is_unitCombo.addItem("")
        self.is_unitCombo.addItem("")
        self.is_unitCombo.addItem("")
        self.is_unitCombo.addItem("")
        self.is_unitCombo.addItem("")
        self.is_unitCombo.addItem("")
        self.is_unitCombo.addItem("")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.is_unitCombo)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.is_methodCombo = QtWidgets.QComboBox(self.groupBox)
        self.is_methodCombo.setObjectName("is_methodCombo")
        self.is_methodCombo.addItem("")
        self.is_methodCombo.addItem("")
        self.is_methodCombo.addItem("")
        self.is_methodCombo.addItem("")
        self.is_methodCombo.addItem("")
        self.is_methodCombo.addItem("")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.is_methodCombo)
        self.is_dbCB = QtWidgets.QCheckBox(self.groupBox)
        self.is_dbCB.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.is_dbCB.setObjectName("is_dbCB")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.is_dbCB)
        self.is_assay_minLE = QtWidgets.QLineEdit(self.groupBox)
        self.is_assay_minLE.setObjectName("is_assay_minLE")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.is_assay_minLE)
        self.is_assay_maxLE = QtWidgets.QLineEdit(self.groupBox)
        self.is_assay_maxLE.setObjectName("is_assay_maxLE")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.is_assay_maxLE)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.is_assay_nameCombo = QtWidgets.QComboBox(self.groupBox)
        self.is_assay_nameCombo.setObjectName("is_assay_nameCombo")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.is_assay_nameCombo)
        self.is_assay_nameLE = QtWidgets.QLineEdit(self.groupBox)
        self.is_assay_nameLE.setEnabled(False)
        self.is_assay_nameLE.setObjectName("is_assay_nameLE")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.is_assay_nameLE)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.acceptB = QtWidgets.QDialogButtonBox(Dialog)
        self.acceptB.setOrientation(QtCore.Qt.Horizontal)
        self.acceptB.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.acceptB.setObjectName("acceptB")
        self.gridLayout.addWidget(self.acceptB, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.acceptB.accepted.connect(Dialog.accept)
        self.acceptB.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.is_assay_minLE, self.is_assay_maxLE)
        Dialog.setTabOrder(self.is_assay_maxLE, self.is_unitCombo)
        Dialog.setTabOrder(self.is_unitCombo, self.is_methodCombo)
        Dialog.setTabOrder(self.is_methodCombo, self.is_dbCB)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "Assay Specifications"))
        self.label.setText(_translate("Dialog", "Assay Name:"))
        self.label_4.setText(_translate("Dialog", "Units:"))
        self.is_unitCombo.setItemText(0, _translate("Dialog", "%"))
        self.is_unitCombo.setItemText(1, _translate("Dialog", "mcg/g"))
        self.is_unitCombo.setItemText(2, _translate("Dialog", "ppm"))
        self.is_unitCombo.setItemText(3, _translate("Dialog", "mg/serving"))
        self.is_unitCombo.setItemText(4, _translate("Dialog", "mg/sg"))
        self.is_unitCombo.setItemText(5, _translate("Dialog", "mg/tablet"))
        self.is_unitCombo.setItemText(6, _translate("Dialog", "mg/capsule"))
        self.label_5.setText(_translate("Dialog", "Assay Method:"))
        self.is_methodCombo.setItemText(0, _translate("Dialog", "HPLC"))
        self.is_methodCombo.setItemText(1, _translate("Dialog", "GC"))
        self.is_methodCombo.setItemText(2, _translate("Dialog", "UV-Vis"))
        self.is_methodCombo.setItemText(3, _translate("Dialog", "ICP-OES"))
        self.is_methodCombo.setItemText(4, _translate("Dialog", "P-NMR"))
        self.is_methodCombo.setItemText(5, _translate("Dialog", "USP"))
        self.is_dbCB.setText(_translate("Dialog", "Dry Basis?"))
        self.label_3.setText(_translate("Dialog", "Assay Min:"))
        self.label_2.setText(_translate("Dialog", "Assay Max:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

