# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dialog_MicroSpec.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(253, 284)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.is_tpc_maxLE = QtWidgets.QLineEdit(self.groupBox)
        self.is_tpc_maxLE.setObjectName("is_tpc_maxLE")
        self.gridLayout_2.addWidget(self.is_tpc_maxLE, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.is_ym_maxLE = QtWidgets.QLineEdit(self.groupBox)
        self.is_ym_maxLE.setObjectName("is_ym_maxLE")
        self.gridLayout_2.addWidget(self.is_ym_maxLE, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.is_ecoliCombo = QtWidgets.QComboBox(self.groupBox)
        self.is_ecoliCombo.setObjectName("is_ecoliCombo")
        self.is_ecoliCombo.addItem("")
        self.is_ecoliCombo.addItem("")
        self.is_ecoliCombo.addItem("")
        self.gridLayout_2.addWidget(self.is_ecoliCombo, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 1)
        self.is_salmonellaCombo = QtWidgets.QComboBox(self.groupBox)
        self.is_salmonellaCombo.setObjectName("is_salmonellaCombo")
        self.is_salmonellaCombo.addItem("")
        self.is_salmonellaCombo.addItem("")
        self.is_salmonellaCombo.addItem("")
        self.gridLayout_2.addWidget(self.is_salmonellaCombo, 3, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 4, 0, 1, 1)
        self.is_staphCombo = QtWidgets.QComboBox(self.groupBox)
        self.is_staphCombo.setObjectName("is_staphCombo")
        self.is_staphCombo.addItem("")
        self.is_staphCombo.addItem("")
        self.is_staphCombo.addItem("")
        self.gridLayout_2.addWidget(self.is_staphCombo, 4, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 5, 0, 1, 3)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 6, 0, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 7, 0, 1, 1)
        self.is_tpc_minLE = QtWidgets.QLineEdit(self.groupBox)
        self.is_tpc_minLE.setObjectName("is_tpc_minLE")
        self.gridLayout_2.addWidget(self.is_tpc_minLE, 7, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 7, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 8, 0, 1, 1)
        self.is_ym_minLE = QtWidgets.QLineEdit(self.groupBox)
        self.is_ym_minLE.setObjectName("is_ym_minLE")
        self.gridLayout_2.addWidget(self.is_ym_minLE, 8, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 8, 2, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.acceptB = QtWidgets.QDialogButtonBox(Dialog)
        self.acceptB.setOrientation(QtCore.Qt.Horizontal)
        self.acceptB.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.acceptB.setObjectName("acceptB")
        self.gridLayout.addWidget(self.acceptB, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.acceptB.accepted.connect(Dialog.accept)
        self.acceptB.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.is_tpc_maxLE, self.is_ym_maxLE)
        Dialog.setTabOrder(self.is_ym_maxLE, self.is_ecoliCombo)
        Dialog.setTabOrder(self.is_ecoliCombo, self.is_salmonellaCombo)
        Dialog.setTabOrder(self.is_salmonellaCombo, self.is_staphCombo)
        Dialog.setTabOrder(self.is_staphCombo, self.is_tpc_minLE)
        Dialog.setTabOrder(self.is_tpc_minLE, self.is_ym_minLE)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "Microbial Specifications"))
        self.label.setText(_translate("Dialog", "TPC Max:"))
        self.label_9.setText(_translate("Dialog", "CFU/g"))
        self.label_2.setText(_translate("Dialog", "Y&M Max:"))
        self.label_10.setText(_translate("Dialog", "CFU/g"))
        self.label_3.setText(_translate("Dialog", "E. Coli:"))
        self.is_ecoliCombo.setItemText(0, _translate("Dialog", "Negative"))
        self.is_ecoliCombo.setItemText(1, _translate("Dialog", "Not Tested"))
        self.is_ecoliCombo.setItemText(2, _translate("Dialog", "Positive"))
        self.label_4.setText(_translate("Dialog", "Salmonella:"))
        self.is_salmonellaCombo.setItemText(0, _translate("Dialog", "Negative"))
        self.is_salmonellaCombo.setItemText(1, _translate("Dialog", "Not Tested"))
        self.is_salmonellaCombo.setItemText(2, _translate("Dialog", "Positive"))
        self.label_5.setText(_translate("Dialog", "Staph:"))
        self.is_staphCombo.setItemText(0, _translate("Dialog", "Negative"))
        self.is_staphCombo.setItemText(1, _translate("Dialog", "Not Tested"))
        self.is_staphCombo.setItemText(2, _translate("Dialog", "Positive"))
        self.label_6.setText(_translate("Dialog", "Probiotics Only:"))
        self.label_7.setText(_translate("Dialog", "TPC Min:"))
        self.label_11.setText(_translate("Dialog", "CFU/g"))
        self.label_8.setText(_translate("Dialog", "Y&M Min:"))
        self.label_12.setText(_translate("Dialog", "CFU/g"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

