# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Window_Main.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(810, 610)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout_11.addWidget(self.label_8, 0, 0, 1, 2)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout_11.addWidget(self.label, 1, 0, 1, 1)
        self.searchT = QtWidgets.QLineEdit(self.centralwidget)
        self.searchT.setObjectName("searchT")
        self.gridLayout_11.addWidget(self.searchT, 1, 1, 1, 1)
        self.searchB = QtWidgets.QPushButton(self.centralwidget)
        self.searchB.setObjectName("searchB")
        self.gridLayout_11.addWidget(self.searchB, 1, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(322, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem, 1, 3, 1, 1)
        self.master_tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.master_tabs.setObjectName("master_tabs")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        spacerItem1 = QtWidgets.QSpacerItem(20, 67, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem1, 6, 3, 1, 1)
        self.groupBox_27 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_27.setObjectName("groupBox_27")
        self.formLayout_4 = QtWidgets.QFormLayout(self.groupBox_27)
        self.formLayout_4.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_15 = QtWidgets.QLabel(self.groupBox_27)
        self.label_15.setObjectName("label_15")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.is_flow_densityL = QtWidgets.QLabel(self.groupBox_27)
        self.is_flow_densityL.setObjectName("is_flow_densityL")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.is_flow_densityL)
        self.label_34 = QtWidgets.QLabel(self.groupBox_27)
        self.label_34.setObjectName("label_34")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_34)
        self.is_tap_densityL = QtWidgets.QLabel(self.groupBox_27)
        self.is_tap_densityL.setObjectName("is_tap_densityL")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.is_tap_densityL)
        self.label_36 = QtWidgets.QLabel(self.groupBox_27)
        self.label_36.setObjectName("label_36")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_36)
        self.is_moistureL = QtWidgets.QLabel(self.groupBox_27)
        self.is_moistureL.setObjectName("is_moistureL")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.is_moistureL)
        self.label_39 = QtWidgets.QLabel(self.groupBox_27)
        self.label_39.setObjectName("label_39")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_39)
        self.is_avgwtL = QtWidgets.QLabel(self.groupBox_27)
        self.is_avgwtL.setObjectName("is_avgwtL")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.is_avgwtL)
        self.gridLayout_12.addWidget(self.groupBox_27, 2, 2, 2, 1)
        self.groupBox_20 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_20.setObjectName("groupBox_20")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_20)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.is_chemList = QtWidgets.QListWidget(self.groupBox_20)
        self.is_chemList.setObjectName("is_chemList")
        self.gridLayout_8.addWidget(self.is_chemList, 0, 0, 3, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem2, 2, 1, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.groupBox_20)
        self.label_49.setObjectName("label_49")
        self.gridLayout_8.addWidget(self.label_49, 0, 1, 1, 1)
        self.is_chem_presenceL = QtWidgets.QLabel(self.groupBox_20)
        self.is_chem_presenceL.setObjectName("is_chem_presenceL")
        self.gridLayout_8.addWidget(self.is_chem_presenceL, 1, 2, 1, 1)
        self.is_chem_methodL = QtWidgets.QLabel(self.groupBox_20)
        self.is_chem_methodL.setObjectName("is_chem_methodL")
        self.gridLayout_8.addWidget(self.is_chem_methodL, 0, 2, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.groupBox_20)
        self.label_50.setObjectName("label_50")
        self.gridLayout_8.addWidget(self.label_50, 1, 1, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox_20, 3, 3, 1, 1)
        self.groupBox_43 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_43.setObjectName("groupBox_43")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_43)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.groupBox_43)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.is_item_notePT = QtWidgets.QPlainTextEdit(self.groupBox_43)
        self.is_item_notePT.setObjectName("is_item_notePT")
        self.gridLayout.addWidget(self.is_item_notePT, 3, 0, 1, 3)
        self.is_item_nameL = QtWidgets.QLabel(self.groupBox_43)
        self.is_item_nameL.setObjectName("is_item_nameL")
        self.gridLayout.addWidget(self.is_item_nameL, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_43)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_43)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.is_item_numberL = QtWidgets.QLabel(self.groupBox_43)
        self.is_item_numberL.setObjectName("is_item_numberL")
        self.gridLayout.addWidget(self.is_item_numberL, 0, 1, 1, 2)
        self.gridLayout_12.addWidget(self.groupBox_43, 1, 1, 3, 1)
        self.groupBox_18 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_18.setObjectName("groupBox_18")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_18)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_54 = QtWidgets.QLabel(self.groupBox_18)
        self.label_54.setObjectName("label_54")
        self.gridLayout_5.addWidget(self.label_54, 1, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_18)
        self.label_14.setObjectName("label_14")
        self.gridLayout_5.addWidget(self.label_14, 0, 1, 1, 1)
        self.is_assay_methodL = QtWidgets.QLabel(self.groupBox_18)
        self.is_assay_methodL.setObjectName("is_assay_methodL")
        self.gridLayout_5.addWidget(self.is_assay_methodL, 1, 2, 1, 1)
        self.is_assay_specL = QtWidgets.QLabel(self.groupBox_18)
        self.is_assay_specL.setObjectName("is_assay_specL")
        self.gridLayout_5.addWidget(self.is_assay_specL, 0, 2, 1, 1)
        self.is_dbL = QtWidgets.QLabel(self.groupBox_18)
        self.is_dbL.setObjectName("is_dbL")
        self.gridLayout_5.addWidget(self.is_dbL, 2, 2, 1, 1)
        self.label_58 = QtWidgets.QLabel(self.groupBox_18)
        self.label_58.setObjectName("label_58")
        self.gridLayout_5.addWidget(self.label_58, 2, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem3, 3, 1, 1, 1)
        self.is_assayList = QtWidgets.QListWidget(self.groupBox_18)
        self.is_assayList.setObjectName("is_assayList")
        self.gridLayout_5.addWidget(self.is_assayList, 0, 0, 4, 1)
        self.gridLayout_12.addWidget(self.groupBox_18, 1, 3, 2, 1)
        self.groupBox_26 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_26.setObjectName("groupBox_26")
        self.formLayout_7 = QtWidgets.QFormLayout(self.groupBox_26)
        self.formLayout_7.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_7.setObjectName("formLayout_7")
        self.label_28 = QtWidgets.QLabel(self.groupBox_26)
        self.label_28.setObjectName("label_28")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_28)
        self.is_colorL = QtWidgets.QLabel(self.groupBox_26)
        self.is_colorL.setObjectName("is_colorL")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.is_colorL)
        self.label_30 = QtWidgets.QLabel(self.groupBox_26)
        self.label_30.setObjectName("label_30")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_30)
        self.is_odorL = QtWidgets.QLabel(self.groupBox_26)
        self.is_odorL.setObjectName("is_odorL")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.is_odorL)
        self.label_32 = QtWidgets.QLabel(self.groupBox_26)
        self.label_32.setObjectName("label_32")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_32)
        self.is_appearanceL = QtWidgets.QLabel(self.groupBox_26)
        self.is_appearanceL.setObjectName("is_appearanceL")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.is_appearanceL)
        self.gridLayout_12.addWidget(self.groupBox_26, 1, 2, 1, 1)
        self.groupBox_44 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_44.setObjectName("groupBox_44")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_44)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setObjectName("formLayout")
        self.label_6 = QtWidgets.QLabel(self.groupBox_44)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.is_allergensL = QtWidgets.QLabel(self.groupBox_44)
        self.is_allergensL.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.is_allergensL.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.is_allergensL.setObjectName("is_allergensL")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.is_allergensL)
        self.label_7 = QtWidgets.QLabel(self.groupBox_44)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.is_fridgeL = QtWidgets.QLabel(self.groupBox_44)
        self.is_fridgeL.setObjectName("is_fridgeL")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.is_fridgeL)
        self.gridLayout_12.addWidget(self.groupBox_44, 4, 1, 1, 1)
        self.groupBox_16 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_16.setObjectName("groupBox_16")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_16)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_17 = QtWidgets.QLabel(self.groupBox_16)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_9.addWidget(self.label_17, 0, 0, 1, 1)
        self.label_80 = QtWidgets.QLabel(self.groupBox_16)
        self.label_80.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_80.setObjectName("label_80")
        self.gridLayout_9.addWidget(self.label_80, 0, 1, 1, 1)
        self.is_as_maxL = QtWidgets.QLabel(self.groupBox_16)
        self.is_as_maxL.setObjectName("is_as_maxL")
        self.gridLayout_9.addWidget(self.is_as_maxL, 0, 2, 1, 1)
        self.is_as_unitL = QtWidgets.QLabel(self.groupBox_16)
        self.is_as_unitL.setObjectName("is_as_unitL")
        self.gridLayout_9.addWidget(self.is_as_unitL, 0, 3, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.groupBox_16)
        self.label_40.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_40.setObjectName("label_40")
        self.gridLayout_9.addWidget(self.label_40, 1, 0, 1, 1)
        self.label_81 = QtWidgets.QLabel(self.groupBox_16)
        self.label_81.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_81.setObjectName("label_81")
        self.gridLayout_9.addWidget(self.label_81, 1, 1, 1, 1)
        self.is_cd_maxL = QtWidgets.QLabel(self.groupBox_16)
        self.is_cd_maxL.setObjectName("is_cd_maxL")
        self.gridLayout_9.addWidget(self.is_cd_maxL, 1, 2, 1, 1)
        self.is_cd_unitL = QtWidgets.QLabel(self.groupBox_16)
        self.is_cd_unitL.setObjectName("is_cd_unitL")
        self.gridLayout_9.addWidget(self.is_cd_unitL, 1, 3, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.groupBox_16)
        self.label_41.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_41.setObjectName("label_41")
        self.gridLayout_9.addWidget(self.label_41, 2, 0, 1, 1)
        self.label_82 = QtWidgets.QLabel(self.groupBox_16)
        self.label_82.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_82.setObjectName("label_82")
        self.gridLayout_9.addWidget(self.label_82, 2, 1, 1, 1)
        self.is_pb_maxL = QtWidgets.QLabel(self.groupBox_16)
        self.is_pb_maxL.setObjectName("is_pb_maxL")
        self.gridLayout_9.addWidget(self.is_pb_maxL, 2, 2, 1, 1)
        self.is_pb_unitL = QtWidgets.QLabel(self.groupBox_16)
        self.is_pb_unitL.setObjectName("is_pb_unitL")
        self.gridLayout_9.addWidget(self.is_pb_unitL, 2, 3, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.groupBox_16)
        self.label_55.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_55.setObjectName("label_55")
        self.gridLayout_9.addWidget(self.label_55, 3, 0, 1, 1)
        self.label_83 = QtWidgets.QLabel(self.groupBox_16)
        self.label_83.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_83.setObjectName("label_83")
        self.gridLayout_9.addWidget(self.label_83, 3, 1, 1, 1)
        self.is_hg_maxL = QtWidgets.QLabel(self.groupBox_16)
        self.is_hg_maxL.setObjectName("is_hg_maxL")
        self.gridLayout_9.addWidget(self.is_hg_maxL, 3, 2, 1, 1)
        self.is_hg_unitL = QtWidgets.QLabel(self.groupBox_16)
        self.is_hg_unitL.setObjectName("is_hg_unitL")
        self.gridLayout_9.addWidget(self.is_hg_unitL, 3, 3, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox_16, 4, 2, 1, 1)
        self.groupBox_19 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_19.setObjectName("groupBox_19")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_19)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_37 = QtWidgets.QLabel(self.groupBox_19)
        self.label_37.setObjectName("label_37")
        self.gridLayout_10.addWidget(self.label_37, 2, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.groupBox_19)
        self.label_25.setObjectName("label_25")
        self.gridLayout_10.addWidget(self.label_25, 1, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupBox_19)
        self.label_21.setObjectName("label_21")
        self.gridLayout_10.addWidget(self.label_21, 0, 1, 1, 1)
        self.is_plant_partL = QtWidgets.QLabel(self.groupBox_19)
        self.is_plant_partL.setObjectName("is_plant_partL")
        self.gridLayout_10.addWidget(self.is_plant_partL, 0, 2, 1, 1)
        self.is_plant_methodL = QtWidgets.QLabel(self.groupBox_19)
        self.is_plant_methodL.setObjectName("is_plant_methodL")
        self.gridLayout_10.addWidget(self.is_plant_methodL, 2, 2, 1, 1)
        self.is_plant_solventL = QtWidgets.QLabel(self.groupBox_19)
        self.is_plant_solventL.setObjectName("is_plant_solventL")
        self.gridLayout_10.addWidget(self.is_plant_solventL, 1, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem4, 3, 1, 1, 1)
        self.is_plantList = QtWidgets.QListWidget(self.groupBox_19)
        self.is_plantList.setObjectName("is_plantList")
        self.gridLayout_10.addWidget(self.is_plantList, 0, 0, 4, 1)
        self.gridLayout_12.addWidget(self.groupBox_19, 4, 3, 1, 1)
        self.groupBox_29 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_29.setObjectName("groupBox_29")
        self.formLayout_3 = QtWidgets.QFormLayout(self.groupBox_29)
        self.formLayout_3.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_18 = QtWidgets.QLabel(self.groupBox_29)
        self.label_18.setObjectName("label_18")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.is_tpcL = QtWidgets.QLabel(self.groupBox_29)
        self.is_tpcL.setObjectName("is_tpcL")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.is_tpcL)
        self.label_20 = QtWidgets.QLabel(self.groupBox_29)
        self.label_20.setObjectName("label_20")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.is_ymL = QtWidgets.QLabel(self.groupBox_29)
        self.is_ymL.setObjectName("is_ymL")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.is_ymL)
        self.label_22 = QtWidgets.QLabel(self.groupBox_29)
        self.label_22.setObjectName("label_22")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.is_ecoliL = QtWidgets.QLabel(self.groupBox_29)
        self.is_ecoliL.setObjectName("is_ecoliL")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.is_ecoliL)
        self.label_24 = QtWidgets.QLabel(self.groupBox_29)
        self.label_24.setObjectName("label_24")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.is_salmonellaL = QtWidgets.QLabel(self.groupBox_29)
        self.is_salmonellaL.setObjectName("is_salmonellaL")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.is_salmonellaL)
        self.label_26 = QtWidgets.QLabel(self.groupBox_29)
        self.label_26.setObjectName("label_26")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_26)
        self.is_staphL = QtWidgets.QLabel(self.groupBox_29)
        self.is_staphL.setObjectName("is_staphL")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.is_staphL)
        self.gridLayout_12.addWidget(self.groupBox_29, 5, 2, 2, 1)
        self.groupBox_17 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_17.setObjectName("groupBox_17")
        self.formLayout_8 = QtWidgets.QFormLayout(self.groupBox_17)
        self.formLayout_8.setObjectName("formLayout_8")
        self.label_84 = QtWidgets.QLabel(self.groupBox_17)
        self.label_84.setObjectName("label_84")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_84)
        self.is_pesticideL = QtWidgets.QLabel(self.groupBox_17)
        self.is_pesticideL.setObjectName("is_pesticideL")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.is_pesticideL)
        self.gridLayout_12.addWidget(self.groupBox_17, 5, 3, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem5, 1, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem6, 5, 1, 2, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem7, 1, 4, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_12.addItem(spacerItem8, 0, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_12.addItem(spacerItem9, 7, 2, 1, 1)
        self.master_tabs.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.tabWidget = QtWidgets.QTabWidget(self.tab_6)
        self.tabWidget.setGeometry(QtCore.QRect(140, 10, 631, 451))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.groupBox_21 = QtWidgets.QGroupBox(self.tab_9)
        self.groupBox_21.setGeometry(QtCore.QRect(10, 200, 291, 211))
        self.groupBox_21.setObjectName("groupBox_21")
        self.formLayout_9 = QtWidgets.QFormLayout(self.groupBox_21)
        self.formLayout_9.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_9.setObjectName("formLayout_9")
        self.label_33 = QtWidgets.QLabel(self.groupBox_21)
        self.label_33.setObjectName("label_33")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_33)
        self.il_expected_dateL = QtWidgets.QLabel(self.groupBox_21)
        self.il_expected_dateL.setObjectName("il_expected_dateL")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.il_expected_dateL)
        self.label_35 = QtWidgets.QLabel(self.groupBox_21)
        self.label_35.setObjectName("label_35")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_35)
        self.il_final_dateL = QtWidgets.QLabel(self.groupBox_21)
        self.il_final_dateL.setObjectName("il_final_dateL")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.il_final_dateL)
        self.label_86 = QtWidgets.QLabel(self.groupBox_21)
        self.label_86.setObjectName("label_86")
        self.formLayout_9.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_86)
        self.il_all_resultsL = QtWidgets.QLabel(self.groupBox_21)
        self.il_all_resultsL.setObjectName("il_all_resultsL")
        self.formLayout_9.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.il_all_resultsL)
        self.il_print_coaB = QtWidgets.QPushButton(self.groupBox_21)
        self.il_print_coaB.setObjectName("il_print_coaB")
        self.formLayout_9.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.il_print_coaB)
        self.il_lot_delayPT = QtWidgets.QPlainTextEdit(self.groupBox_21)
        self.il_lot_delayPT.setObjectName("il_lot_delayPT")
        self.formLayout_9.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.il_lot_delayPT)
        self.label_31 = QtWidgets.QLabel(self.groupBox_21)
        self.label_31.setObjectName("label_31")
        self.formLayout_9.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_31)
        self.il_save_lot_delayB = QtWidgets.QPushButton(self.groupBox_21)
        self.il_save_lot_delayB.setObjectName("il_save_lot_delayB")
        self.formLayout_9.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.il_save_lot_delayB)
        self.groupBox_22 = QtWidgets.QGroupBox(self.tab_9)
        self.groupBox_22.setGeometry(QtCore.QRect(410, 140, 201, 94))
        self.groupBox_22.setObjectName("groupBox_22")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox_22)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_27 = QtWidgets.QLabel(self.groupBox_22)
        self.label_27.setObjectName("label_27")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_27)
        self.il_facilityL = QtWidgets.QLabel(self.groupBox_22)
        self.il_facilityL.setObjectName("il_facilityL")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.il_facilityL)
        self.label_29 = QtWidgets.QLabel(self.groupBox_22)
        self.label_29.setObjectName("label_29")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_29)
        self.il_wh_codeL = QtWidgets.QLabel(self.groupBox_22)
        self.il_wh_codeL.setObjectName("il_wh_codeL")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.il_wh_codeL)
        self.il_moveB = QtWidgets.QPushButton(self.groupBox_22)
        self.il_moveB.setObjectName("il_moveB")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.il_moveB)
        self.groupBox_23 = QtWidgets.QGroupBox(self.tab_9)
        self.groupBox_23.setGeometry(QtCore.QRect(10, 10, 291, 171))
        self.groupBox_23.setObjectName("groupBox_23")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_23)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.il_lot_notePT = QtWidgets.QPlainTextEdit(self.groupBox_23)
        self.il_lot_notePT.setObjectName("il_lot_notePT")
        self.gridLayout_3.addWidget(self.il_lot_notePT, 3, 1, 1, 2)
        self.label_9 = QtWidgets.QLabel(self.groupBox_23)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 1, 0, 1, 1)
        self.il_vendorL = QtWidgets.QLabel(self.groupBox_23)
        self.il_vendorL.setObjectName("il_vendorL")
        self.gridLayout_3.addWidget(self.il_vendorL, 1, 1, 1, 1)
        self.label_94 = QtWidgets.QLabel(self.groupBox_23)
        self.label_94.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_94.setObjectName("label_94")
        self.gridLayout_3.addWidget(self.label_94, 2, 0, 1, 1)
        self.il_vendor_lotL = QtWidgets.QLabel(self.groupBox_23)
        self.il_vendor_lotL.setObjectName("il_vendor_lotL")
        self.gridLayout_3.addWidget(self.il_vendor_lotL, 2, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_23)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 3, 0, 1, 1)
        self.il_save_lot_noteB = QtWidgets.QPushButton(self.groupBox_23)
        self.il_save_lot_noteB.setObjectName("il_save_lot_noteB")
        self.gridLayout_3.addWidget(self.il_save_lot_noteB, 4, 2, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox_23)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 0, 0, 1, 1)
        self.il_lot_numberL = QtWidgets.QLabel(self.groupBox_23)
        self.il_lot_numberL.setObjectName("il_lot_numberL")
        self.gridLayout_3.addWidget(self.il_lot_numberL, 0, 1, 1, 1)
        self.groupBox_24 = QtWidgets.QGroupBox(self.tab_9)
        self.groupBox_24.setGeometry(QtCore.QRect(410, 250, 201, 151))
        self.groupBox_24.setObjectName("groupBox_24")
        self.formLayout_6 = QtWidgets.QFormLayout(self.groupBox_24)
        self.formLayout_6.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_16 = QtWidgets.QLabel(self.groupBox_24)
        self.label_16.setObjectName("label_16")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.il_amount_remainingL = QtWidgets.QLabel(self.groupBox_24)
        self.il_amount_remainingL.setObjectName("il_amount_remainingL")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.il_amount_remainingL)
        self.label_23 = QtWidgets.QLabel(self.groupBox_24)
        self.label_23.setObjectName("label_23")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.il_amount_in_aL = QtWidgets.QLabel(self.groupBox_24)
        self.il_amount_in_aL.setObjectName("il_amount_in_aL")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.il_amount_in_aL)
        self.label_43 = QtWidgets.QLabel(self.groupBox_24)
        self.label_43.setObjectName("label_43")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_43)
        self.il_amount_in_rL = QtWidgets.QLabel(self.groupBox_24)
        self.il_amount_in_rL.setObjectName("il_amount_in_rL")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.il_amount_in_rL)
        self.label_44 = QtWidgets.QLabel(self.groupBox_24)
        self.label_44.setObjectName("label_44")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_44)
        self.il_amount_in_qL = QtWidgets.QLabel(self.groupBox_24)
        self.il_amount_in_qL.setObjectName("il_amount_in_qL")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.il_amount_in_qL)
        self.label_45 = QtWidgets.QLabel(self.groupBox_24)
        self.label_45.setObjectName("label_45")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_45)
        self.il_amount_in_acL = QtWidgets.QLabel(self.groupBox_24)
        self.il_amount_in_acL.setObjectName("il_amount_in_acL")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.il_amount_in_acL)
        self.pushButton = QtWidgets.QPushButton(self.groupBox_24)
        self.pushButton.setObjectName("pushButton")
        self.formLayout_6.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.pushButton)
        self.groupBox_25 = QtWidgets.QGroupBox(self.tab_9)
        self.groupBox_25.setGeometry(QtCore.QRect(411, 10, 201, 111))
        self.groupBox_25.setObjectName("groupBox_25")
        self.formLayout_10 = QtWidgets.QFormLayout(self.groupBox_25)
        self.formLayout_10.setObjectName("formLayout_10")
        self.label_13 = QtWidgets.QLabel(self.groupBox_25)
        self.label_13.setObjectName("label_13")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.il_amount_recL = QtWidgets.QLabel(self.groupBox_25)
        self.il_amount_recL.setObjectName("il_amount_recL")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.il_amount_recL)
        self.label_11 = QtWidgets.QLabel(self.groupBox_25)
        self.label_11.setObjectName("label_11")
        self.formLayout_10.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.il_date_recL = QtWidgets.QLabel(self.groupBox_25)
        self.il_date_recL.setObjectName("il_date_recL")
        self.formLayout_10.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.il_date_recL)
        self.label_10 = QtWidgets.QLabel(self.groupBox_25)
        self.label_10.setObjectName("label_10")
        self.formLayout_10.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.il_rec_poL = QtWidgets.QLabel(self.groupBox_25)
        self.il_rec_poL.setObjectName("il_rec_poL")
        self.formLayout_10.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.il_rec_poL)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_25)
        self.pushButton_2.setObjectName("pushButton_2")
        self.formLayout_10.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.pushButton_2)
        self.tabWidget.addTab(self.tab_9, "")
        self.tab_13 = QtWidgets.QWidget()
        self.tab_13.setObjectName("tab_13")
        self.groupBox_14 = QtWidgets.QGroupBox(self.tab_13)
        self.groupBox_14.setGeometry(QtCore.QRect(10, 260, 181, 71))
        self.groupBox_14.setObjectName("groupBox_14")
        self.formLayout_22 = QtWidgets.QFormLayout(self.groupBox_14)
        self.formLayout_22.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_22.setObjectName("formLayout_22")
        self.label_76 = QtWidgets.QLabel(self.groupBox_14)
        self.label_76.setObjectName("label_76")
        self.formLayout_22.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_76)
        self.il_lab1L = QtWidgets.QLabel(self.groupBox_14)
        self.il_lab1L.setObjectName("il_lab1L")
        self.formLayout_22.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.il_lab1L)
        self.label_129 = QtWidgets.QLabel(self.groupBox_14)
        self.label_129.setObjectName("label_129")
        self.formLayout_22.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_129)
        self.il_price1L = QtWidgets.QLabel(self.groupBox_14)
        self.il_price1L.setObjectName("il_price1L")
        self.formLayout_22.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.il_price1L)
        self.groupBox_15 = QtWidgets.QGroupBox(self.tab_13)
        self.groupBox_15.setGeometry(QtCore.QRect(410, 260, 201, 71))
        self.groupBox_15.setObjectName("groupBox_15")
        self.formLayout_23 = QtWidgets.QFormLayout(self.groupBox_15)
        self.formLayout_23.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_23.setObjectName("formLayout_23")
        self.label_131 = QtWidgets.QLabel(self.groupBox_15)
        self.label_131.setObjectName("label_131")
        self.formLayout_23.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_131)
        self.il_po1L = QtWidgets.QLabel(self.groupBox_15)
        self.il_po1L.setObjectName("il_po1L")
        self.formLayout_23.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.il_po1L)
        self.label_133 = QtWidgets.QLabel(self.groupBox_15)
        self.label_133.setObjectName("label_133")
        self.formLayout_23.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_133)
        self.il_tracking1L = QtWidgets.QLabel(self.groupBox_15)
        self.il_tracking1L.setObjectName("il_tracking1L")
        self.formLayout_23.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.il_tracking1L)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_13)
        self.groupBox_5.setGeometry(QtCore.QRect(210, 260, 181, 91))
        self.groupBox_5.setObjectName("groupBox_5")
        self.formLayout_24 = QtWidgets.QFormLayout(self.groupBox_5)
        self.formLayout_24.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_24.setObjectName("formLayout_24")
        self.label_134 = QtWidgets.QLabel(self.groupBox_5)
        self.label_134.setObjectName("label_134")
        self.formLayout_24.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_134)
        self.il_sent_date1L = QtWidgets.QLabel(self.groupBox_5)
        self.il_sent_date1L.setObjectName("il_sent_date1L")
        self.formLayout_24.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.il_sent_date1L)
        self.label_136 = QtWidgets.QLabel(self.groupBox_5)
        self.label_136.setObjectName("label_136")
        self.formLayout_24.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_136)
        self.il_expected_date1L = QtWidgets.QLabel(self.groupBox_5)
        self.il_expected_date1L.setObjectName("il_expected_date1L")
        self.formLayout_24.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.il_expected_date1L)
        self.label_138 = QtWidgets.QLabel(self.groupBox_5)
        self.label_138.setObjectName("label_138")
        self.formLayout_24.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_138)
        self.il_result_date1L = QtWidgets.QLabel(self.groupBox_5)
        self.il_result_date1L.setObjectName("il_result_date1L")
        self.formLayout_24.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.il_result_date1L)
        self.groupBox = QtWidgets.QGroupBox(self.tab_13)
        self.groupBox.setGeometry(QtCore.QRect(210, 10, 181, 221))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.il_chem_id_resultList = QtWidgets.QListWidget(self.groupBox)
        self.il_chem_id_resultList.setObjectName("il_chem_id_resultList")
        self.gridLayout_2.addWidget(self.il_chem_id_resultList, 0, 0, 1, 1)
        self.formLayout_27 = QtWidgets.QFormLayout()
        self.formLayout_27.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_27.setObjectName("formLayout_27")
        self.label_71 = QtWidgets.QLabel(self.groupBox)
        self.label_71.setObjectName("label_71")
        self.formLayout_27.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_71)
        self.il_chem_id_specL = QtWidgets.QLabel(self.groupBox)
        self.il_chem_id_specL.setObjectName("il_chem_id_specL")
        self.formLayout_27.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.il_chem_id_specL)
        self.label_114 = QtWidgets.QLabel(self.groupBox)
        self.label_114.setObjectName("label_114")
        self.formLayout_27.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_114)
        self.il_chem_id_resultL = QtWidgets.QLabel(self.groupBox)
        self.il_chem_id_resultL.setObjectName("il_chem_id_resultL")
        self.formLayout_27.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.il_chem_id_resultL)
        self.gridLayout_2.addLayout(self.formLayout_27, 1, 0, 1, 1)
        self.groupBox_13 = QtWidgets.QGroupBox(self.tab_13)
        self.groupBox_13.setGeometry(QtCore.QRect(410, 10, 201, 221))
        self.groupBox_13.setObjectName("groupBox_13")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_13)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.il_plant_id_resultTable = QtWidgets.QTableWidget(self.groupBox_13)
        self.il_plant_id_resultTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.il_plant_id_resultTable.setObjectName("il_plant_id_resultTable")
        self.il_plant_id_resultTable.setColumnCount(2)
        self.il_plant_id_resultTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.il_plant_id_resultTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.il_plant_id_resultTable.setHorizontalHeaderItem(1, item)
        self.il_plant_id_resultTable.horizontalHeader().setStretchLastSection(True)
        self.il_plant_id_resultTable.verticalHeader().setVisible(False)
        self.gridLayout_6.addWidget(self.il_plant_id_resultTable, 0, 0, 1, 1)
        self.formLayout_18 = QtWidgets.QFormLayout()
        self.formLayout_18.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_18.setObjectName("formLayout_18")
        self.label_79 = QtWidgets.QLabel(self.groupBox_13)
        self.label_79.setObjectName("label_79")
        self.formLayout_18.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_79)
        self.il_plant_id_specL = QtWidgets.QLabel(self.groupBox_13)
        self.il_plant_id_specL.setObjectName("il_plant_id_specL")
        self.formLayout_18.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.il_plant_id_specL)
        self.label_115 = QtWidgets.QLabel(self.groupBox_13)
        self.label_115.setObjectName("label_115")
        self.formLayout_18.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_115)
        self.il_plant_id_resultL = QtWidgets.QLabel(self.groupBox_13)
        self.il_plant_id_resultL.setObjectName("il_plant_id_resultL")
        self.formLayout_18.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.il_plant_id_resultL)
        self.gridLayout_6.addLayout(self.formLayout_18, 1, 0, 1, 1)
        self.groupBox_48 = QtWidgets.QGroupBox(self.tab_13)
        self.groupBox_48.setGeometry(QtCore.QRect(10, 10, 181, 221))
        self.groupBox_48.setObjectName("groupBox_48")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_48)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.il_assay_resultList = QtWidgets.QListWidget(self.groupBox_48)
        self.il_assay_resultList.setObjectName("il_assay_resultList")
        self.gridLayout_7.addWidget(self.il_assay_resultList, 0, 0, 1, 1)
        self.formLayout_19 = QtWidgets.QFormLayout()
        self.formLayout_19.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_19.setObjectName("formLayout_19")
        self.label_99 = QtWidgets.QLabel(self.groupBox_48)
        self.label_99.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_99.setObjectName("label_99")
        self.formLayout_19.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_99)
        self.il_assay_specL = QtWidgets.QLabel(self.groupBox_48)
        self.il_assay_specL.setObjectName("il_assay_specL")
        self.formLayout_19.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.il_assay_specL)
        self.label_100 = QtWidgets.QLabel(self.groupBox_48)
        self.label_100.setObjectName("label_100")
        self.formLayout_19.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_100)
        self.il_assay_resultL = QtWidgets.QLabel(self.groupBox_48)
        self.il_assay_resultL.setObjectName("il_assay_resultL")
        self.formLayout_19.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.il_assay_resultL)
        self.gridLayout_7.addLayout(self.formLayout_19, 1, 0, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_13)
        self.pushButton_9.setGeometry(QtCore.QRect(490, 390, 119, 23))
        self.pushButton_9.setObjectName("pushButton_9")
        self.il_enter_assayB = QtWidgets.QPushButton(self.tab_13)
        self.il_enter_assayB.setGeometry(QtCore.QRect(350, 390, 119, 23))
        self.il_enter_assayB.setObjectName("il_enter_assayB")
        self.tabWidget.addTab(self.tab_13, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.groupBox_45 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_45.setGeometry(QtCore.QRect(210, 10, 181, 151))
        self.groupBox_45.setObjectName("groupBox_45")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox_45)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.il_hmTable = QtWidgets.QTableWidget(self.groupBox_45)
        self.il_hmTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.il_hmTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.il_hmTable.setColumnCount(1)
        self.il_hmTable.setObjectName("il_hmTable")
        self.il_hmTable.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.il_hmTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.il_hmTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.il_hmTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.il_hmTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.il_hmTable.setHorizontalHeaderItem(0, item)
        self.il_hmTable.horizontalHeader().setVisible(False)
        self.il_hmTable.horizontalHeader().setStretchLastSection(True)
        self.il_hmTable.verticalHeader().setStretchLastSection(True)
        self.gridLayout_13.addWidget(self.il_hmTable, 0, 0, 1, 2)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_6.setGeometry(QtCore.QRect(210, 260, 181, 91))
        self.groupBox_6.setObjectName("groupBox_6")
        self.formLayout_28 = QtWidgets.QFormLayout(self.groupBox_6)
        self.formLayout_28.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_28.setObjectName("formLayout_28")
        self.label_140 = QtWidgets.QLabel(self.groupBox_6)
        self.label_140.setObjectName("label_140")
        self.formLayout_28.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_140)
        self.il_sent_date2L = QtWidgets.QLabel(self.groupBox_6)
        self.il_sent_date2L.setObjectName("il_sent_date2L")
        self.formLayout_28.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.il_sent_date2L)
        self.label_142 = QtWidgets.QLabel(self.groupBox_6)
        self.label_142.setObjectName("label_142")
        self.formLayout_28.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_142)
        self.il_expected_date2L = QtWidgets.QLabel(self.groupBox_6)
        self.il_expected_date2L.setObjectName("il_expected_date2L")
        self.formLayout_28.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.il_expected_date2L)
        self.label_144 = QtWidgets.QLabel(self.groupBox_6)
        self.label_144.setObjectName("label_144")
        self.formLayout_28.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_144)
        self.il_result_date2L = QtWidgets.QLabel(self.groupBox_6)
        self.il_result_date2L.setObjectName("il_result_date2L")
        self.formLayout_28.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.il_result_date2L)
        self.groupBox_28 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_28.setGeometry(QtCore.QRect(10, 260, 181, 65))
        self.groupBox_28.setObjectName("groupBox_28")
        self.formLayout_32 = QtWidgets.QFormLayout(self.groupBox_28)
        self.formLayout_32.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_32.setObjectName("formLayout_32")
        self.label_77 = QtWidgets.QLabel(self.groupBox_28)
        self.label_77.setObjectName("label_77")
        self.formLayout_32.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_77)
        self.il_lab2L = QtWidgets.QLabel(self.groupBox_28)
        self.il_lab2L.setObjectName("il_lab2L")
        self.formLayout_32.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.il_lab2L)
        self.label_190 = QtWidgets.QLabel(self.groupBox_28)
        self.label_190.setObjectName("label_190")
        self.formLayout_32.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_190)
        self.il_price2L = QtWidgets.QLabel(self.groupBox_28)
        self.il_price2L.setObjectName("il_price2L")
        self.formLayout_32.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.il_price2L)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 181, 181))
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.il_microTable = QtWidgets.QTableWidget(self.groupBox_3)
        self.il_microTable.setColumnCount(1)
        self.il_microTable.setObjectName("il_microTable")
        self.il_microTable.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.il_microTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.il_microTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.il_microTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.il_microTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.il_microTable.setVerticalHeaderItem(4, item)
        self.il_microTable.horizontalHeader().setVisible(False)
        self.il_microTable.horizontalHeader().setStretchLastSection(True)
        self.il_microTable.verticalHeader().setStretchLastSection(True)
        self.gridLayout_14.addWidget(self.il_microTable, 0, 0, 1, 1)
        self.groupBox_38 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_38.setGeometry(QtCore.QRect(410, 260, 201, 71))
        self.groupBox_38.setObjectName("groupBox_38")
        self.formLayout_29 = QtWidgets.QFormLayout(self.groupBox_38)
        self.formLayout_29.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_29.setObjectName("formLayout_29")
        self.label_147 = QtWidgets.QLabel(self.groupBox_38)
        self.label_147.setObjectName("label_147")
        self.formLayout_29.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_147)
        self.il_po2L = QtWidgets.QLabel(self.groupBox_38)
        self.il_po2L.setObjectName("il_po2L")
        self.formLayout_29.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.il_po2L)
        self.label_149 = QtWidgets.QLabel(self.groupBox_38)
        self.label_149.setObjectName("label_149")
        self.formLayout_29.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_149)
        self.il_tracking2L = QtWidgets.QLabel(self.groupBox_38)
        self.il_tracking2L.setObjectName("il_tracking2L")
        self.formLayout_29.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.il_tracking2L)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_2.setGeometry(QtCore.QRect(410, 10, 201, 91))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.il_pesticideTable = QtWidgets.QTableWidget(self.groupBox_2)
        self.il_pesticideTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.il_pesticideTable.setTabKeyNavigation(True)
        self.il_pesticideTable.setProperty("showDropIndicator", True)
        self.il_pesticideTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.il_pesticideTable.setColumnCount(1)
        self.il_pesticideTable.setObjectName("il_pesticideTable")
        self.il_pesticideTable.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.il_pesticideTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.il_pesticideTable.setVerticalHeaderItem(1, item)
        self.il_pesticideTable.horizontalHeader().setVisible(False)
        self.il_pesticideTable.horizontalHeader().setStretchLastSection(True)
        self.il_pesticideTable.verticalHeader().setStretchLastSection(True)
        self.gridLayout_15.addWidget(self.il_pesticideTable, 0, 0, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_6.setGeometry(QtCore.QRect(530, 390, 75, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        self.il_enter_microB = QtWidgets.QPushButton(self.tab_4)
        self.il_enter_microB.setGeometry(QtCore.QRect(440, 390, 75, 23))
        self.il_enter_microB.setObjectName("il_enter_microB")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab_10)
        self.groupBox_9.setGeometry(QtCore.QRect(10, 10, 191, 201))
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_9)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_46 = QtWidgets.QLabel(self.groupBox_9)
        self.label_46.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_46.setObjectName("label_46")
        self.gridLayout_4.addWidget(self.label_46, 0, 0, 1, 1)
        self.il_color_specL = QtWidgets.QLabel(self.groupBox_9)
        self.il_color_specL.setObjectName("il_color_specL")
        self.gridLayout_4.addWidget(self.il_color_specL, 0, 1, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.groupBox_9)
        self.label_47.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_47.setObjectName("label_47")
        self.gridLayout_4.addWidget(self.label_47, 1, 0, 1, 1)
        self.label_118 = QtWidgets.QLabel(self.groupBox_9)
        self.label_118.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_118.setObjectName("label_118")
        self.gridLayout_4.addWidget(self.label_118, 3, 0, 1, 1)
        self.il_color_resultL = QtWidgets.QLabel(self.groupBox_9)
        self.il_color_resultL.setObjectName("il_color_resultL")
        self.gridLayout_4.addWidget(self.il_color_resultL, 1, 1, 1, 1)
        self.il_odor_specL = QtWidgets.QLabel(self.groupBox_9)
        self.il_odor_specL.setObjectName("il_odor_specL")
        self.gridLayout_4.addWidget(self.il_odor_specL, 3, 1, 1, 1)
        self.label_121 = QtWidgets.QLabel(self.groupBox_9)
        self.label_121.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_121.setObjectName("label_121")
        self.gridLayout_4.addWidget(self.label_121, 7, 0, 1, 1)
        self.il_enter_organolepticsB = QtWidgets.QPushButton(self.groupBox_9)
        self.il_enter_organolepticsB.setObjectName("il_enter_organolepticsB")
        self.gridLayout_4.addWidget(self.il_enter_organolepticsB, 8, 1, 1, 1)
        self.il_appearance_resultL = QtWidgets.QLabel(self.groupBox_9)
        self.il_appearance_resultL.setObjectName("il_appearance_resultL")
        self.gridLayout_4.addWidget(self.il_appearance_resultL, 7, 1, 1, 1)
        self.il_appearance_specL = QtWidgets.QLabel(self.groupBox_9)
        self.il_appearance_specL.setObjectName("il_appearance_specL")
        self.gridLayout_4.addWidget(self.il_appearance_specL, 6, 1, 1, 1)
        self.il_odor_resultL = QtWidgets.QLabel(self.groupBox_9)
        self.il_odor_resultL.setObjectName("il_odor_resultL")
        self.gridLayout_4.addWidget(self.il_odor_resultL, 4, 1, 1, 1)
        self.label_119 = QtWidgets.QLabel(self.groupBox_9)
        self.label_119.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_119.setObjectName("label_119")
        self.gridLayout_4.addWidget(self.label_119, 4, 0, 1, 1)
        self.label_120 = QtWidgets.QLabel(self.groupBox_9)
        self.label_120.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_120.setObjectName("label_120")
        self.gridLayout_4.addWidget(self.label_120, 6, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.groupBox_9)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_4.addWidget(self.line_2, 5, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.groupBox_9)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_4.addWidget(self.line, 2, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.groupBox_9)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_4.addWidget(self.line_3, 2, 1, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.groupBox_9)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_4.addWidget(self.line_4, 5, 1, 1, 1)
        self.groupBox_35 = QtWidgets.QGroupBox(self.tab_10)
        self.groupBox_35.setGeometry(QtCore.QRect(220, 10, 181, 94))
        self.groupBox_35.setObjectName("groupBox_35")
        self.formLayout_13 = QtWidgets.QFormLayout(self.groupBox_35)
        self.formLayout_13.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_13.setObjectName("formLayout_13")
        self.label_56 = QtWidgets.QLabel(self.groupBox_35)
        self.label_56.setObjectName("label_56")
        self.formLayout_13.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_56)
        self.il_moisture_specL = QtWidgets.QLabel(self.groupBox_35)
        self.il_moisture_specL.setObjectName("il_moisture_specL")
        self.formLayout_13.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.il_moisture_specL)
        self.label_61 = QtWidgets.QLabel(self.groupBox_35)
        self.label_61.setObjectName("label_61")
        self.formLayout_13.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_61)
        self.il_moisture_resultL = QtWidgets.QLabel(self.groupBox_35)
        self.il_moisture_resultL.setObjectName("il_moisture_resultL")
        self.formLayout_13.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.il_moisture_resultL)
        self.il_enter_moistureB = QtWidgets.QPushButton(self.groupBox_35)
        self.il_enter_moistureB.setObjectName("il_enter_moistureB")
        self.formLayout_13.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.il_enter_moistureB)
        self.groupBox_36 = QtWidgets.QGroupBox(self.tab_10)
        self.groupBox_36.setGeometry(QtCore.QRect(220, 110, 181, 101))
        self.groupBox_36.setObjectName("groupBox_36")
        self.formLayout_14 = QtWidgets.QFormLayout(self.groupBox_36)
        self.formLayout_14.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_14.setObjectName("formLayout_14")
        self.label_63 = QtWidgets.QLabel(self.groupBox_36)
        self.label_63.setObjectName("label_63")
        self.formLayout_14.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_63)
        self.il_density_specL = QtWidgets.QLabel(self.groupBox_36)
        self.il_density_specL.setObjectName("il_density_specL")
        self.formLayout_14.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.il_density_specL)
        self.label_65 = QtWidgets.QLabel(self.groupBox_36)
        self.label_65.setObjectName("label_65")
        self.formLayout_14.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_65)
        self.il_density_resultL = QtWidgets.QLabel(self.groupBox_36)
        self.il_density_resultL.setObjectName("il_density_resultL")
        self.formLayout_14.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.il_density_resultL)
        self.il_enter_densityB = QtWidgets.QPushButton(self.groupBox_36)
        self.il_enter_densityB.setObjectName("il_enter_densityB")
        self.formLayout_14.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.il_enter_densityB)
        self.groupBox_37 = QtWidgets.QGroupBox(self.tab_10)
        self.groupBox_37.setGeometry(QtCore.QRect(220, 220, 181, 94))
        self.groupBox_37.setObjectName("groupBox_37")
        self.formLayout_15 = QtWidgets.QFormLayout(self.groupBox_37)
        self.formLayout_15.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_15.setObjectName("formLayout_15")
        self.label_67 = QtWidgets.QLabel(self.groupBox_37)
        self.label_67.setObjectName("label_67")
        self.formLayout_15.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_67)
        self.il_avgwt_specL = QtWidgets.QLabel(self.groupBox_37)
        self.il_avgwt_specL.setObjectName("il_avgwt_specL")
        self.formLayout_15.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.il_avgwt_specL)
        self.label_92 = QtWidgets.QLabel(self.groupBox_37)
        self.label_92.setObjectName("label_92")
        self.formLayout_15.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_92)
        self.il_avgwt_resultL = QtWidgets.QLabel(self.groupBox_37)
        self.il_avgwt_resultL.setObjectName("il_avgwt_resultL")
        self.formLayout_15.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.il_avgwt_resultL)
        self.il_enter_avgwtB = QtWidgets.QPushButton(self.groupBox_37)
        self.il_enter_avgwtB.setObjectName("il_enter_avgwtB")
        self.formLayout_15.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.il_enter_avgwtB)
        self.tabWidget.addTab(self.tab_10, "")
        self.layoutWidget = QtWidgets.QWidget(self.tab_6)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 121, 311))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.il_lotList = QtWidgets.QListWidget(self.layoutWidget)
        self.il_lotList.setObjectName("il_lotList")
        self.verticalLayout_4.addWidget(self.il_lotList)
        self.master_tabs.addTab(self.tab_6, "")
        self.gridLayout_11.addWidget(self.master_tabs, 2, 0, 1, 4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 810, 21))
        self.menubar.setObjectName("menubar")
        self.menu_file = QtWidgets.QMenu(self.menubar)
        self.menu_file.setObjectName("menu_file")
        self.menu_new = QtWidgets.QMenu(self.menubar)
        self.menu_new.setObjectName("menu_new")
        self.menuRemove = QtWidgets.QMenu(self.menubar)
        self.menuRemove.setObjectName("menuRemove")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menu_printCoA = QtWidgets.QAction(MainWindow)
        self.menu_printCoA.setObjectName("menu_printCoA")
        self.actionPrint_Spec_Sheet = QtWidgets.QAction(MainWindow)
        self.actionPrint_Spec_Sheet.setObjectName("actionPrint_Spec_Sheet")
        self.menu_addChemSpec = QtWidgets.QAction(MainWindow)
        self.menu_addChemSpec.setObjectName("menu_addChemSpec")
        self.actionRemove_Botanical_ID = QtWidgets.QAction(MainWindow)
        self.actionRemove_Botanical_ID.setObjectName("actionRemove_Botanical_ID")
        self.actionRemove_Chemical_ID_2 = QtWidgets.QAction(MainWindow)
        self.actionRemove_Chemical_ID_2.setObjectName("actionRemove_Chemical_ID_2")
        self.menu_addBotSpec = QtWidgets.QAction(MainWindow)
        self.menu_addBotSpec.setObjectName("menu_addBotSpec")
        self.actionEdit_Botanical_ID = QtWidgets.QAction(MainWindow)
        self.actionEdit_Botanical_ID.setObjectName("actionEdit_Botanical_ID")
        self.actionRemove_Botanical_ID_2 = QtWidgets.QAction(MainWindow)
        self.actionRemove_Botanical_ID_2.setObjectName("actionRemove_Botanical_ID_2")
        self.menu_newItem = QtWidgets.QAction(MainWindow)
        self.menu_newItem.setObjectName("menu_newItem")
        self.menu_addAssay = QtWidgets.QAction(MainWindow)
        self.menu_addAssay.setObjectName("menu_addAssay")
        self.menu_addPhys = QtWidgets.QAction(MainWindow)
        self.menu_addPhys.setObjectName("menu_addPhys")
        self.menu_addMicro = QtWidgets.QAction(MainWindow)
        self.menu_addMicro.setObjectName("menu_addMicro")
        self.menu_newItem_2 = QtWidgets.QAction(MainWindow)
        self.menu_newItem_2.setObjectName("menu_newItem_2")
        self.menu_editBasic = QtWidgets.QAction(MainWindow)
        self.menu_editBasic.setObjectName("menu_editBasic")
        self.menu_editChem = QtWidgets.QAction(MainWindow)
        self.menu_editChem.setObjectName("menu_editChem")
        self.menu_editPlant = QtWidgets.QAction(MainWindow)
        self.menu_editPlant.setObjectName("menu_editPlant")
        self.menu_editAssay = QtWidgets.QAction(MainWindow)
        self.menu_editAssay.setObjectName("menu_editAssay")
        self.menu_editPhys = QtWidgets.QAction(MainWindow)
        self.menu_editPhys.setObjectName("menu_editPhys")
        self.menu_editMicro = QtWidgets.QAction(MainWindow)
        self.menu_editMicro.setObjectName("menu_editMicro")
        self.menu_deleteChem = QtWidgets.QAction(MainWindow)
        self.menu_deleteChem.setObjectName("menu_deleteChem")
        self.menu_deletePlant = QtWidgets.QAction(MainWindow)
        self.menu_deletePlant.setObjectName("menu_deletePlant")
        self.menu_deleteAssay = QtWidgets.QAction(MainWindow)
        self.menu_deleteAssay.setObjectName("menu_deleteAssay")
        self.menu_newLot = QtWidgets.QAction(MainWindow)
        self.menu_newLot.setObjectName("menu_newLot")
        self.actionEdit_Lot_Basic_Info = QtWidgets.QAction(MainWindow)
        self.actionEdit_Lot_Basic_Info.setObjectName("actionEdit_Lot_Basic_Info")
        self.menu_removeItem = QtWidgets.QAction(MainWindow)
        self.menu_removeItem.setObjectName("menu_removeItem")
        self.menu_removeLot = QtWidgets.QAction(MainWindow)
        self.menu_removeLot.setObjectName("menu_removeLot")
        self.menu_newAssay = QtWidgets.QAction(MainWindow)
        self.menu_newAssay.setObjectName("menu_newAssay")
        self.menu_removeAssay = QtWidgets.QAction(MainWindow)
        self.menu_removeAssay.setObjectName("menu_removeAssay")
        self.menu_editAssay_2 = QtWidgets.QAction(MainWindow)
        self.menu_editAssay_2.setObjectName("menu_editAssay_2")
        self.menu_editHM = QtWidgets.QAction(MainWindow)
        self.menu_editHM.setObjectName("menu_editHM")
        self.menu_editOrganoleptics = QtWidgets.QAction(MainWindow)
        self.menu_editOrganoleptics.setObjectName("menu_editOrganoleptics")
        self.menu_editPhysicals = QtWidgets.QAction(MainWindow)
        self.menu_editPhysicals.setObjectName("menu_editPhysicals")
        self.menu_editMicrobes = QtWidgets.QAction(MainWindow)
        self.menu_editMicrobes.setObjectName("menu_editMicrobes")
        self.menu_editBasic_2 = QtWidgets.QAction(MainWindow)
        self.menu_editBasic_2.setObjectName("menu_editBasic_2")
        self.menu_newChem = QtWidgets.QAction(MainWindow)
        self.menu_newChem.setObjectName("menu_newChem")
        self.menu_newPlant = QtWidgets.QAction(MainWindow)
        self.menu_newPlant.setObjectName("menu_newPlant")
        self.menu_editChem_2 = QtWidgets.QAction(MainWindow)
        self.menu_editChem_2.setObjectName("menu_editChem_2")
        self.menu_editPlant_2 = QtWidgets.QAction(MainWindow)
        self.menu_editPlant_2.setObjectName("menu_editPlant_2")
        self.menu_editPesticides = QtWidgets.QAction(MainWindow)
        self.menu_editPesticides.setObjectName("menu_editPesticides")
        self.menu_removeChem = QtWidgets.QAction(MainWindow)
        self.menu_removeChem.setObjectName("menu_removeChem")
        self.menu_removePlant = QtWidgets.QAction(MainWindow)
        self.menu_removePlant.setObjectName("menu_removePlant")
        self.menu_file.addAction(self.menu_printCoA)
        self.menu_new.addAction(self.menu_newItem_2)
        self.menu_new.addAction(self.menu_newAssay)
        self.menu_new.addAction(self.menu_newChem)
        self.menu_new.addAction(self.menu_newPlant)
        self.menu_new.addSeparator()
        self.menu_new.addAction(self.menu_newLot)
        self.menuRemove.addAction(self.menu_removeItem)
        self.menuRemove.addAction(self.menu_removeAssay)
        self.menuRemove.addAction(self.menu_removeChem)
        self.menuRemove.addAction(self.menu_removePlant)
        self.menuRemove.addSeparator()
        self.menuRemove.addAction(self.menu_removeLot)
        self.menuEdit.addAction(self.menu_editBasic_2)
        self.menuEdit.addAction(self.menu_editAssay_2)
        self.menuEdit.addAction(self.menu_editChem_2)
        self.menuEdit.addAction(self.menu_editPlant_2)
        self.menuEdit.addAction(self.menu_editHM)
        self.menuEdit.addAction(self.menu_editOrganoleptics)
        self.menuEdit.addAction(self.menu_editPhysicals)
        self.menuEdit.addAction(self.menu_editMicrobes)
        self.menuEdit.addAction(self.menu_editPesticides)
        self.menubar.addAction(self.menu_file.menuAction())
        self.menubar.addAction(self.menu_new.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuRemove.menuAction())

        self.retranslateUi(MainWindow)
        self.master_tabs.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_8.setText(_translate("MainWindow", "Enter a raw item number to begin."))
        self.label.setText(_translate("MainWindow", "Search:"))
        self.searchB.setText(_translate("MainWindow", "Search"))
        self.groupBox_27.setTitle(_translate("MainWindow", "Physical Testing"))
        self.label_15.setText(_translate("MainWindow", "Flow Density:"))
        self.is_flow_densityL.setText(_translate("MainWindow", "N/A"))
        self.label_34.setText(_translate("MainWindow", "Tap Density:"))
        self.is_tap_densityL.setText(_translate("MainWindow", "N/A"))
        self.label_36.setText(_translate("MainWindow", "Moisture:"))
        self.is_moistureL.setText(_translate("MainWindow", "N/A"))
        self.label_39.setText(_translate("MainWindow", "Average Weight:"))
        self.is_avgwtL.setText(_translate("MainWindow", "N/A"))
        self.groupBox_20.setTitle(_translate("MainWindow", "Chemical Identification"))
        self.label_49.setText(_translate("MainWindow", "Method:"))
        self.is_chem_presenceL.setText(_translate("MainWindow", "N/A"))
        self.is_chem_methodL.setText(_translate("MainWindow", "N/A"))
        self.label_50.setText(_translate("MainWindow", "Presence:"))
        self.groupBox_43.setTitle(_translate("MainWindow", "Basic Info"))
        self.label_5.setText(_translate("MainWindow", "Item Notes:"))
        self.is_item_nameL.setText(_translate("MainWindow", "N/A"))
        self.label_4.setText(_translate("MainWindow", "Item Name:"))
        self.label_2.setText(_translate("MainWindow", "Item Number:"))
        self.is_item_numberL.setText(_translate("MainWindow", "Search for an Item #"))
        self.groupBox_18.setTitle(_translate("MainWindow", "Assays"))
        self.label_54.setText(_translate("MainWindow", "Method:"))
        self.label_14.setText(_translate("MainWindow", "Specification:"))
        self.is_assay_methodL.setText(_translate("MainWindow", "N/A"))
        self.is_assay_specL.setText(_translate("MainWindow", "N/A"))
        self.is_dbL.setText(_translate("MainWindow", "N/A"))
        self.label_58.setText(_translate("MainWindow", "Dry Basis:"))
        self.groupBox_26.setTitle(_translate("MainWindow", "Organoleptics"))
        self.label_28.setText(_translate("MainWindow", "Color:"))
        self.is_colorL.setText(_translate("MainWindow", "N/A"))
        self.label_30.setText(_translate("MainWindow", "Odor:"))
        self.is_odorL.setText(_translate("MainWindow", "N/A"))
        self.label_32.setText(_translate("MainWindow", "Appearance:"))
        self.is_appearanceL.setText(_translate("MainWindow", "N/A"))
        self.groupBox_44.setTitle(_translate("MainWindow", "Storage"))
        self.label_6.setText(_translate("MainWindow", "FDA-8 Allergens:"))
        self.is_allergensL.setText(_translate("MainWindow", "None"))
        self.label_7.setText(_translate("MainWindow", "Requires Refridgeration?:"))
        self.is_fridgeL.setText(_translate("MainWindow", "No"))
        self.groupBox_16.setTitle(_translate("MainWindow", "Heavy Metals"))
        self.label_17.setText(_translate("MainWindow", "Arsenic:"))
        self.label_80.setText(_translate("MainWindow", "<"))
        self.is_as_maxL.setText(_translate("MainWindow", "5"))
        self.is_as_unitL.setText(_translate("MainWindow", "ppm"))
        self.label_40.setText(_translate("MainWindow", "Cadmium:"))
        self.label_81.setText(_translate("MainWindow", "<"))
        self.is_cd_maxL.setText(_translate("MainWindow", "0.3"))
        self.is_cd_unitL.setText(_translate("MainWindow", "ppm"))
        self.label_41.setText(_translate("MainWindow", "Lead:"))
        self.label_82.setText(_translate("MainWindow", "<"))
        self.is_pb_maxL.setText(_translate("MainWindow", "10"))
        self.is_pb_unitL.setText(_translate("MainWindow", "ppm"))
        self.label_55.setText(_translate("MainWindow", "Mercury:"))
        self.label_83.setText(_translate("MainWindow", "<"))
        self.is_hg_maxL.setText(_translate("MainWindow", "0.2"))
        self.is_hg_unitL.setText(_translate("MainWindow", "ppm"))
        self.groupBox_19.setTitle(_translate("MainWindow", "Botanical Identification"))
        self.label_37.setText(_translate("MainWindow", "Method:"))
        self.label_25.setText(_translate("MainWindow", "Solvent:"))
        self.label_21.setText(_translate("MainWindow", "Plant Part:"))
        self.is_plant_partL.setText(_translate("MainWindow", "N/A"))
        self.is_plant_methodL.setText(_translate("MainWindow", "N/A"))
        self.is_plant_solventL.setText(_translate("MainWindow", "N/A"))
        self.groupBox_29.setTitle(_translate("MainWindow", "Microbial Tests"))
        self.label_18.setText(_translate("MainWindow", "Total Plate Count:"))
        self.is_tpcL.setText(_translate("MainWindow", "N/A"))
        self.label_20.setText(_translate("MainWindow", "Yeast & Mold:"))
        self.is_ymL.setText(_translate("MainWindow", "N/A"))
        self.label_22.setText(_translate("MainWindow", "E. Coli:"))
        self.is_ecoliL.setText(_translate("MainWindow", "Negative"))
        self.label_24.setText(_translate("MainWindow", "Salmonella:"))
        self.is_salmonellaL.setText(_translate("MainWindow", "Negative"))
        self.label_26.setText(_translate("MainWindow", "Staph:"))
        self.is_staphL.setText(_translate("MainWindow", "Negative"))
        self.groupBox_17.setTitle(_translate("MainWindow", "Pesticides"))
        self.label_84.setText(_translate("MainWindow", "Presence:"))
        self.is_pesticideL.setText(_translate("MainWindow", "N/A"))
        self.master_tabs.setTabText(self.master_tabs.indexOf(self.tab_5), _translate("MainWindow", "Item Specifications"))
        self.groupBox_21.setTitle(_translate("MainWindow", "Quality"))
        self.label_33.setText(_translate("MainWindow", "Expected Release Date:"))
        self.il_expected_dateL.setText(_translate("MainWindow", "N/A"))
        self.label_35.setText(_translate("MainWindow", "Final Release Date:"))
        self.il_final_dateL.setText(_translate("MainWindow", "N/A"))
        self.label_86.setText(_translate("MainWindow", "All Results In?:"))
        self.il_all_resultsL.setText(_translate("MainWindow", "No"))
        self.il_print_coaB.setText(_translate("MainWindow", "Print CoA"))
        self.label_31.setText(_translate("MainWindow", "Delays:"))
        self.il_save_lot_delayB.setText(_translate("MainWindow", "Save Delay"))
        self.groupBox_22.setTitle(_translate("MainWindow", "Location"))
        self.label_27.setText(_translate("MainWindow", "Facility:"))
        self.il_facilityL.setText(_translate("MainWindow", "N/A"))
        self.label_29.setText(_translate("MainWindow", "WH Code:"))
        self.il_wh_codeL.setText(_translate("MainWindow", "N/A"))
        self.il_moveB.setText(_translate("MainWindow", "Move"))
        self.groupBox_23.setTitle(_translate("MainWindow", "Basic Lot Info"))
        self.label_9.setText(_translate("MainWindow", "Vendor:"))
        self.il_vendorL.setText(_translate("MainWindow", "N/A"))
        self.label_94.setText(_translate("MainWindow", "Vendor Lot:"))
        self.il_vendor_lotL.setText(_translate("MainWindow", "N/A"))
        self.label_12.setText(_translate("MainWindow", "Lot Notes:"))
        self.il_save_lot_noteB.setText(_translate("MainWindow", "Save Note"))
        self.label_19.setText(_translate("MainWindow", "Lot Number:"))
        self.il_lot_numberL.setText(_translate("MainWindow", "Select Lot"))
        self.groupBox_24.setTitle(_translate("MainWindow", "Sage Data"))
        self.label_16.setText(_translate("MainWindow", "Amount Remaining:"))
        self.il_amount_remainingL.setText(_translate("MainWindow", "N/A"))
        self.label_23.setText(_translate("MainWindow", "Amount in A:"))
        self.il_amount_in_aL.setText(_translate("MainWindow", "N/A"))
        self.label_43.setText(_translate("MainWindow", "Amount in R:"))
        self.il_amount_in_rL.setText(_translate("MainWindow", "N/A"))
        self.label_44.setText(_translate("MainWindow", "Amount in Q:"))
        self.il_amount_in_qL.setText(_translate("MainWindow", "N/A"))
        self.label_45.setText(_translate("MainWindow", "Amount in AC:"))
        self.il_amount_in_acL.setText(_translate("MainWindow", "N/A"))
        self.pushButton.setText(_translate("MainWindow", "Edit"))
        self.groupBox_25.setTitle(_translate("MainWindow", "Recieving"))
        self.label_13.setText(_translate("MainWindow", "Amount Received:"))
        self.il_amount_recL.setText(_translate("MainWindow", "N/A"))
        self.label_11.setText(_translate("MainWindow", "Date Received:"))
        self.il_date_recL.setText(_translate("MainWindow", "N/A"))
        self.label_10.setText(_translate("MainWindow", "Receiving PO:"))
        self.il_rec_poL.setText(_translate("MainWindow", "N/A"))
        self.pushButton_2.setText(_translate("MainWindow", "Edit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_9), _translate("MainWindow", "Lot Info"))
        self.groupBox_14.setTitle(_translate("MainWindow", "Lab Info"))
        self.label_76.setText(_translate("MainWindow", "Testing Lab:"))
        self.il_lab1L.setText(_translate("MainWindow", "Not Sent"))
        self.label_129.setText(_translate("MainWindow", "Test Price:"))
        self.il_price1L.setText(_translate("MainWindow", "N/A"))
        self.groupBox_15.setTitle(_translate("MainWindow", "Tracking"))
        self.label_131.setText(_translate("MainWindow", "PO #:"))
        self.il_po1L.setText(_translate("MainWindow", "N/A"))
        self.label_133.setText(_translate("MainWindow", "Tracking #:"))
        self.il_tracking1L.setText(_translate("MainWindow", "N/A"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Dates"))
        self.label_134.setText(_translate("MainWindow", "Date Sent:"))
        self.il_sent_date1L.setText(_translate("MainWindow", "Not Sent"))
        self.label_136.setText(_translate("MainWindow", "Expected Date:"))
        self.il_expected_date1L.setText(_translate("MainWindow", "N/A"))
        self.label_138.setText(_translate("MainWindow", "Actual Result Date:"))
        self.il_result_date1L.setText(_translate("MainWindow", "N/A"))
        self.groupBox.setTitle(_translate("MainWindow", "Chemical IDs"))
        self.label_71.setText(_translate("MainWindow", "Spec:"))
        self.il_chem_id_specL.setText(_translate("MainWindow", "Positive"))
        self.label_114.setText(_translate("MainWindow", "Result:"))
        self.il_chem_id_resultL.setText(_translate("MainWindow", "Not Sent"))
        self.groupBox_13.setTitle(_translate("MainWindow", "Botanical IDs"))
        item = self.il_plant_id_resultTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Genus"))
        item = self.il_plant_id_resultTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Species"))
        self.label_79.setText(_translate("MainWindow", "Spec:"))
        self.il_plant_id_specL.setText(_translate("MainWindow", "Positive"))
        self.label_115.setText(_translate("MainWindow", "Result:"))
        self.il_plant_id_resultL.setText(_translate("MainWindow", "Not Sent"))
        self.groupBox_48.setTitle(_translate("MainWindow", "Assays"))
        self.label_99.setText(_translate("MainWindow", "Spec:"))
        self.il_assay_specL.setText(_translate("MainWindow", "N/A"))
        self.label_100.setText(_translate("MainWindow", "Result:"))
        self.il_assay_resultL.setText(_translate("MainWindow", "Not Sent"))
        self.pushButton_9.setText(_translate("MainWindow", "Send Out"))
        self.il_enter_assayB.setText(_translate("MainWindow", "Enter Result"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_13), _translate("MainWindow", "ID and Assay Results"))
        self.groupBox_45.setTitle(_translate("MainWindow", "Heavy Metals"))
        item = self.il_hmTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Arsenic"))
        item = self.il_hmTable.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Cadmium"))
        item = self.il_hmTable.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Lead"))
        item = self.il_hmTable.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Mercury"))
        item = self.il_hmTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Result"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Dates"))
        self.label_140.setText(_translate("MainWindow", "Date Sent:"))
        self.il_sent_date2L.setText(_translate("MainWindow", "Not Sent"))
        self.label_142.setText(_translate("MainWindow", "Expected Date:"))
        self.il_expected_date2L.setText(_translate("MainWindow", "N/A"))
        self.label_144.setText(_translate("MainWindow", "Actual Result Date:"))
        self.il_result_date2L.setText(_translate("MainWindow", "N/A"))
        self.groupBox_28.setTitle(_translate("MainWindow", "Lab Info"))
        self.label_77.setText(_translate("MainWindow", "Testing Lab:"))
        self.il_lab2L.setText(_translate("MainWindow", "Not Sent"))
        self.label_190.setText(_translate("MainWindow", "Test Price:"))
        self.il_price2L.setText(_translate("MainWindow", "N/A"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Microbes"))
        item = self.il_microTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "TPC"))
        item = self.il_microTable.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Y&M"))
        item = self.il_microTable.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "E. Coli"))
        item = self.il_microTable.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Salmonella"))
        item = self.il_microTable.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "Staph"))
        self.groupBox_38.setTitle(_translate("MainWindow", "Tracking"))
        self.label_147.setText(_translate("MainWindow", "PO #:"))
        self.il_po2L.setText(_translate("MainWindow", "N/A"))
        self.label_149.setText(_translate("MainWindow", "Tracking #:"))
        self.il_tracking2L.setText(_translate("MainWindow", "N/A"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Pesticides"))
        item = self.il_pesticideTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Standard"))
        item = self.il_pesticideTable.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Result"))
        self.pushButton_6.setText(_translate("MainWindow", "Send Out"))
        self.il_enter_microB.setText(_translate("MainWindow", "Enter Results"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "HM, MP/YM, and Pesticide Results"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Organoleptics"))
        self.label_46.setText(_translate("MainWindow", "Color Spec:"))
        self.il_color_specL.setText(_translate("MainWindow", "N/A"))
        self.label_47.setText(_translate("MainWindow", "Result:"))
        self.label_118.setText(_translate("MainWindow", "Odor Spec:"))
        self.il_color_resultL.setText(_translate("MainWindow", "N/A"))
        self.il_odor_specL.setText(_translate("MainWindow", "N/A"))
        self.label_121.setText(_translate("MainWindow", "Result:"))
        self.il_enter_organolepticsB.setText(_translate("MainWindow", "Enter Results"))
        self.il_appearance_resultL.setText(_translate("MainWindow", "N/A"))
        self.il_appearance_specL.setText(_translate("MainWindow", "N/A"))
        self.il_odor_resultL.setText(_translate("MainWindow", "N/A"))
        self.label_119.setText(_translate("MainWindow", "Result:"))
        self.label_120.setText(_translate("MainWindow", "Appearance Spec:"))
        self.groupBox_35.setTitle(_translate("MainWindow", "Moisture"))
        self.label_56.setText(_translate("MainWindow", "Specification:"))
        self.il_moisture_specL.setText(_translate("MainWindow", "N/A"))
        self.label_61.setText(_translate("MainWindow", "Result:"))
        self.il_moisture_resultL.setText(_translate("MainWindow", "N/A"))
        self.il_enter_moistureB.setText(_translate("MainWindow", "Enter Moisture"))
        self.groupBox_36.setTitle(_translate("MainWindow", "Density"))
        self.label_63.setText(_translate("MainWindow", "Specification:"))
        self.il_density_specL.setText(_translate("MainWindow", "N/A"))
        self.label_65.setText(_translate("MainWindow", "Result:"))
        self.il_density_resultL.setText(_translate("MainWindow", "N/A"))
        self.il_enter_densityB.setText(_translate("MainWindow", "Enter Density"))
        self.groupBox_37.setTitle(_translate("MainWindow", "Average Weight"))
        self.label_67.setText(_translate("MainWindow", "Specification:"))
        self.il_avgwt_specL.setText(_translate("MainWindow", "N/A"))
        self.label_92.setText(_translate("MainWindow", "Result:"))
        self.il_avgwt_resultL.setText(_translate("MainWindow", "N/A"))
        self.il_enter_avgwtB.setText(_translate("MainWindow", "Enter Avg. Wt."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_10), _translate("MainWindow", "Physical Results"))
        self.label_3.setText(_translate("MainWindow", "Item Lots:"))
        self.master_tabs.setTabText(self.master_tabs.indexOf(self.tab_6), _translate("MainWindow", "Item Lots"))
        self.menu_file.setTitle(_translate("MainWindow", "File"))
        self.menu_new.setTitle(_translate("MainWindow", "New"))
        self.menuRemove.setTitle(_translate("MainWindow", "Remove"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menu_printCoA.setText(_translate("MainWindow", "Print Spec Sheet"))
        self.actionPrint_Spec_Sheet.setText(_translate("MainWindow", "Print Spec Sheet"))
        self.menu_addChemSpec.setText(_translate("MainWindow", "New Chemical ID"))
        self.actionRemove_Botanical_ID.setText(_translate("MainWindow", "Edit Chemical ID"))
        self.actionRemove_Chemical_ID_2.setText(_translate("MainWindow", "Remove Chemical ID"))
        self.menu_addBotSpec.setText(_translate("MainWindow", "New Botanical ID"))
        self.actionEdit_Botanical_ID.setText(_translate("MainWindow", "Edit Botanical ID"))
        self.actionRemove_Botanical_ID_2.setText(_translate("MainWindow", "Remove Botanical ID"))
        self.menu_newItem.setText(_translate("MainWindow", "New Item"))
        self.menu_addAssay.setText(_translate("MainWindow", "New Assay"))
        self.menu_addPhys.setText(_translate("MainWindow", "New Physical Spec"))
        self.menu_addMicro.setText(_translate("MainWindow", "New Microbial Spec"))
        self.menu_newItem_2.setText(_translate("MainWindow", "Item"))
        self.menu_editBasic.setText(_translate("MainWindow", "Edit Item Basic Info"))
        self.menu_editChem.setText(_translate("MainWindow", "Edit Selected Chemical ID"))
        self.menu_editPlant.setText(_translate("MainWindow", "Edit Selected Botanical ID"))
        self.menu_editAssay.setText(_translate("MainWindow", "Edit Selected Assay"))
        self.menu_editPhys.setText(_translate("MainWindow", "Edit Physical Spec"))
        self.menu_editMicro.setText(_translate("MainWindow", "Edit Microbial Spec"))
        self.menu_deleteChem.setText(_translate("MainWindow", "Delete Selected Chemical ID"))
        self.menu_deletePlant.setText(_translate("MainWindow", "Delete Selected Botanical ID"))
        self.menu_deleteAssay.setText(_translate("MainWindow", "Delete Selected Assay"))
        self.menu_newLot.setText(_translate("MainWindow", "Lot"))
        self.actionEdit_Lot_Basic_Info.setText(_translate("MainWindow", "Edit Lot Basic Info"))
        self.menu_removeItem.setText(_translate("MainWindow", "Current Item"))
        self.menu_removeLot.setText(_translate("MainWindow", "Selected Lot"))
        self.menu_newAssay.setText(_translate("MainWindow", "Assay"))
        self.menu_removeAssay.setText(_translate("MainWindow", "Selected Assay"))
        self.menu_editAssay_2.setText(_translate("MainWindow", "Selected Assay"))
        self.menu_editHM.setText(_translate("MainWindow", "Heavy Metals"))
        self.menu_editOrganoleptics.setText(_translate("MainWindow", "Organoleptics"))
        self.menu_editPhysicals.setText(_translate("MainWindow", "Physical Tests"))
        self.menu_editMicrobes.setText(_translate("MainWindow", "Microbial Tests"))
        self.menu_editBasic_2.setText(_translate("MainWindow", "Basic Info"))
        self.menu_newChem.setText(_translate("MainWindow", "Chemical ID"))
        self.menu_newPlant.setText(_translate("MainWindow", "Botanical ID"))
        self.menu_editChem_2.setText(_translate("MainWindow", "Selected Chemical ID"))
        self.menu_editPlant_2.setText(_translate("MainWindow", "Selected Botanical ID"))
        self.menu_editPesticides.setText(_translate("MainWindow", "Pesticides Standard"))
        self.menu_removeChem.setText(_translate("MainWindow", "Selected Chemical ID"))
        self.menu_removePlant.setText(_translate("MainWindow", "Selected Botanical ID"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

